/**
 * tests/cli/skills.test.ts — the skills command through its real surface: it
 * writes a pack where it is told to, rewrites it in place byte for byte, and
 * removes only what it wrote.
 *
 * Everything happens inside a tmpdir, including the default-location case,
 * which runs with the working directory moved so that "beside the project"
 * never means beside this repository or anyone's home.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { main } from '../../src/cli/index.ts';

interface Capture {
  readonly code: number;
  readonly out: string;
  readonly err: string;
}

/** Run CLI steps against one throwaway directory, with the real home out of reach. */
async function run(steps: (root: string) => ReadonlyArray<string[]>): Promise<Capture & { root: string }> {
  const root = mkdtempSync(join(tmpdir(), 'construct-skills-'));
  const previousData = process.env.XDG_DATA_HOME;
  const previousCache = process.env.XDG_CACHE_HOME;
  process.env.XDG_DATA_HOME = join(root, 'share');
  process.env.XDG_CACHE_HOME = join(root, 'cache');
  const out: string[] = [];
  const err: string[] = [];
  const realOut = process.stdout.write.bind(process.stdout);
  const realErr = process.stderr.write.bind(process.stderr);
  (process.stdout as { write: unknown }).write = (chunk: string) => {
    out.push(String(chunk));
    return true;
  };
  (process.stderr as { write: unknown }).write = (chunk: string) => {
    err.push(String(chunk));
    return true;
  };
  let code = 0;
  try {
    for (const step of steps(root)) code = await main(step);
    return { code, out: out.join(''), err: err.join(''), root };
  } finally {
    (process.stdout as { write: unknown }).write = realOut;
    (process.stderr as { write: unknown }).write = realErr;
    if (previousData === undefined) delete process.env.XDG_DATA_HOME;
    else process.env.XDG_DATA_HOME = previousData;
    if (previousCache === undefined) delete process.env.XDG_CACHE_HOME;
    else process.env.XDG_CACHE_HOME = previousCache;
  }
}

function folders(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

function snapshot(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const folder of folders(dir)) {
    files[folder] = readFileSync(join(dir, folder, 'SKILL.md'), 'utf8');
  }
  return files;
}

test('--out writes a stamped pack, and running it again rewrites the same bytes', async () => {
  const first = await run((root) => [['skills', `--out=${join(root, 'pack')}`]]);
  try {
    assert.equal(first.code, 0);
    const dir = join(first.root, 'pack');
    const written = snapshot(dir);
    const names = Object.keys(written);
    assert.ok(names.length > 0);
    assert.ok(names.every((n) => n.startsWith('construct-')));
    assert.match(first.out, /skills: \d+ skill\(s\) written to /);
    assert.match(first.out, /construct skills --uninstall/);
    for (const name of names) {
      assert.match(written[name], /^\s+generator: construct$/m);
      assert.match(written[name], /^\s+version: \S+$/m);
      assert.match(first.out, new RegExp(`wrote ${name}/SKILL\\.md`));
    }

    // Rewriting in place, byte for byte, is what makes a stale pack fixable by
    // re-running rather than by diffing.
    const again = await run(() => [['skills', `--out=${dir}`]]);
    assert.equal(again.code, 0);
    assert.deepEqual(snapshot(dir), written);
    rmSync(again.root, { recursive: true, force: true });
  } finally {
    rmSync(first.root, { recursive: true, force: true });
  }
});

test('--uninstall removes the generated folders and keeps everything else', async () => {
  const result = await run((root) => {
    const dir = join(root, 'pack');
    mkdirSync(join(dir, 'hand-authored'), { recursive: true });
    writeFileSync(
      join(dir, 'hand-authored', 'SKILL.md'),
      '---\nname: hand-authored\ndescription: written by a person\n---\n\n# Mine\n',
    );
    return [
      ['skills', `--out=${dir}`],
      ['skills', '--uninstall', `--out=${dir}`],
    ];
  });
  try {
    assert.equal(result.code, 0);
    const dir = join(result.root, 'pack');
    assert.deepEqual(folders(dir), ['hand-authored']);
    assert.match(result.out, /kept\s+hand-authored — no generation marker/);
    assert.match(result.out, /removed construct-compliance — generated by construct /);
    assert.match(result.out, /skills: removed \d+, kept 1 in /);
    assert.ok(
      readFileSync(join(dir, 'hand-authored', 'SKILL.md'), 'utf8').includes('written by a person'),
    );
  } finally {
    rmSync(result.root, { recursive: true, force: true });
  }
});

test('--uninstall on a directory that was never written says so and changes nothing', async () => {
  const result = await run((root) => [['skills', '--uninstall', `--out=${join(root, 'absent')}`]]);
  try {
    assert.equal(result.code, 0);
    assert.match(result.out, /nothing to remove/);
    assert.deepEqual(folders(result.root), []);
  } finally {
    rmSync(result.root, { recursive: true, force: true });
  }
});

test('with no --out the pack lands beside the project, under .claude/skills', async () => {
  const previousCwd = process.cwd();
  const result = await run((root) => {
    process.chdir(root);
    return [['skills']];
  });
  try {
    assert.equal(result.code, 0);
    assert.ok(folders(join(result.root, '.claude', 'skills')).includes('construct-security'));
  } finally {
    process.chdir(previousCwd);
    rmSync(result.root, { recursive: true, force: true });
  }
});

test('a flag the command does not know is refused rather than guessed at', async () => {
  const result = await run((root) => [['skills', '--force', `--out=${join(root, 'pack')}`]]);
  try {
    assert.equal(result.code, 2);
    assert.match(result.err, /usage: construct skills/);
    assert.deepEqual(folders(result.root), []);
  } finally {
    rmSync(result.root, { recursive: true, force: true });
  }
});

test('the command is listed in the usage line', async () => {
  const result = await run(() => [['help']]);
  try {
    assert.match(result.out, /\|skills\|/);
  } finally {
    rmSync(result.root, { recursive: true, force: true });
  }
});
