#!/usr/bin/env node
/**
 * tests/e2e/host-suite.mjs — self-driving entry for the host-emulation suite.
 *
 * Runs the deterministic, CI-safe layers (host→MCP emulation, config fidelity +
 * secret scan, non-invocation inertness, artifact-quality gate) and writes a
 * committed, inspectable audit report to tests/e2e/reports/host-emulation-suite.md
 * so the whole run is auditable after the fact. One command, no LLM, no network.
 *
 * The real-LLM layer (Layer 4 execution) is opt-in: it requires a host that can
 * dispatch the specialist chain, so it is driven separately and its produced
 * artifact is scored with lib/artifact-quality.mjs (proven here by fixture).
 *
 * Usage: node tests/e2e/host-suite.mjs   (exits non-zero if any layer fails)
 */

import { spawnSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..', '..');
const REPORT = join(HERE, 'reports', 'host-emulation-suite.md');

const LAYERS = [
  { layer: 1, name: 'Host → MCP emulation', file: 'tests/functional/host-mcp-emulation.functional.test.mjs',
    proves: 'A host connects to the construct MCP server over stdio and exercises skills (loaded + audited in skill-calls.jsonl), templates, and specialist routing (orchestration_policy).' },
  { layer: 2, name: 'Config fidelity + parity + secret scan', file: 'tests/functional/host-config-parity.functional.test.mjs',
    proves: 'Every selected host gets its canonical config + key shape; construct-mcp is wired for all of them; no config inlines a secret; global never seeds unsolicited config.' },
  { layer: 3, name: 'Not invoking Construct = normal', file: 'tests/functional/construct-not-invoked-is-inert.functional.test.mjs',
    proves: 'CONSTRUCT_ROLES=off makes the role machinery inert; a non-cx subagent is untouched; hooks never break the host.' },
  { layer: 4, name: 'Artifact-quality gate (validator)', file: 'tests/e2e/artifact-quality.test.mjs',
    proves: 'The gate that judges a real PRD/evidence-brief (template sections + prose paragraphs + sourced research) passes a good artifact and fails a flat one.' },
];

function runSuite(file) {
  const res = spawnSync(process.execPath, ['--test', file], { cwd: REPO, encoding: 'utf8', timeout: 180_000 });
  const out = (res.stdout || '') + (res.stderr || '');
  const num = (re) => Number((out.match(re) || [])[1] || 0);
  return { ok: res.status === 0, tests: num(/tests (\d+)/), pass: num(/pass (\d+)/), fail: num(/fail (\d+)/) };
}

const rows = LAYERS.map((l) => ({ ...l, ...runSuite(l.file) }));
const allOk = rows.every((r) => r.ok);

const lines = [];
lines.push('<!--');
lines.push('tests/e2e/reports/host-emulation-suite.md — audit report for the self-driving host-emulation suite.');
lines.push('');
lines.push('Generated by tests/e2e/host-suite.mjs. Re-run that to regenerate. Deterministic layers only;');
lines.push('the opt-in real-LLM artifact run is driven separately and scored by lib/artifact-quality.mjs.');
lines.push('-->');
lines.push('');
lines.push('# Host-emulation suite — audit report');
lines.push('');
lines.push(`> ${allOk ? 'All deterministic layers PASS.' : 'FAILURES present — see table.'} Sterile, no-LLM, CI-safe. Run: \`node tests/e2e/host-suite.mjs\`.`);
lines.push('');
lines.push('| Layer | Suite | Tests | Pass | Fail | What it proves |');
lines.push('| --- | --- | --- | --- | --- | --- |');
for (const r of rows) {
  const status = r.ok ? '✅' : '❌';
  lines.push(`| ${status} ${r.layer} | ${r.name} | ${r.tests} | ${r.pass} | ${r.fail} | ${r.proves} |`);
}
lines.push('');
lines.push('## Auditable evidence each layer reads');
lines.push('');
lines.push('- Skill loads → `~/.construct/skill-calls.jsonl`; specialist dispatch/handoff → `<project>/.construct/agent-log.jsonl`, `~/.construct/role-pending.jsonl`.');
lines.push('- Config disposition → adapter dirs + `.construct/` gitignored; shareable artifacts tracked.');
lines.push('- Contract enforcement → `~/.construct/contract-violations.jsonl` (empty on a clean run).');
lines.push('- Artifact quality → `lintDocStructure` (template sections) + prose/citation heuristics in `lib/artifact-quality.mjs`.');
lines.push('');
lines.push('## Opt-in real-LLM layer');
lines.push('');
lines.push('Drive the specialist chain on a host to produce a PRD (`rnd` profile) and an evidence brief (`research` profile), then score each with `assessArtifactQuality(path, type)` and assert the audit trail shows skills + specialists ran. Gated because it requires a model + host subagent dispatch.');
lines.push('');

mkdirSync(dirname(REPORT), { recursive: true });
writeFileSync(REPORT, lines.join('\n') + '\n');

process.stdout.write(`[host-suite] ${allOk ? 'PASS' : 'FAIL'} — ${rows.filter((r) => r.ok).length}/${rows.length} layers green. Report: ${REPORT}\n`);
for (const r of rows) process.stdout.write(`  ${r.ok ? 'ok ' : 'FAIL'} L${r.layer} ${r.name} (${r.pass}/${r.tests})\n`);
process.exit(allOk ? 0 : 1);
