#!/usr/bin/env node
/**
 * tests/e2e/runner.mjs — orchestrator for the Construct end-to-end owner-review
 * pass.
 *
 * Spins up three sterile, isolated environments (greenfield Next.js, established
 * noisy project, research corpus), drives the seven tiers in each, and writes a
 * self-contained Markdown report per scenario plus a cross-scenario summary.
 *
 * Isolation contract: every scenario gets its own tmpdir, its own HOME and
 * CONSTRUCT_HOME_OVERRIDE so no machine state leaks in or out, and its own git init.
 * Cleanup is this runner's job; on failure the tmpdir is preserved and its path
 * printed for forensics.
 *
 * Modes:
 *   --skeleton      Emit the report scaffolding (tiers, real command counts,
 *                   verdict grid, peer rows) without building fixtures or making
 *                   model calls. The owner-review checkpoint for Sequencing
 *                   step 1.
 *   --scenario=a|b|c|all   Which scenario(s) to run (default: all).
 *   --report-dir=<path>    Override the report output directory.
 *
 * The skeleton mode is the only mode wired in this commit; fixture execution and
 * the live tiers land in the per-scenario sequencing steps.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { enumerateCommands } from './lib/command-sweeper.mjs';
import { VERDICT_COLUMNS } from './lib/owner-verdict.mjs';
import { PEER_ROWS } from './lib/peer-comparison.mjs';
import { CONTRACT_VERSION } from '../../lib/embedded-contract/contract-version.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..');
const DEFAULT_REPORT_DIR = join(HERE, 'reports');

export const SCENARIOS = {
  a: {
    id: 'a',
    title: 'Greenfield Next.js',
    workspacePreset: 'rnd',
    reportFile: 'scenario-a-greenfield-nextjs.md',
    fixture: 'npx create-next-app (TypeScript, Tailwind, ESLint, app router, src dir)',
    tier3Artifact: 'ADR for the routing-layer choice (architect → engineer → reviewer)',
    peer: 'A',
  },
  b: {
    id: 'b',
    title: 'Established noisy project',
    workspacePreset: 'rnd',
    reportFile: 'scenario-b-established-noisy.md',
    fixture: 'real OSS TypeScript clone + pre-seeded noise (AGENTS.md, .cursor/, .claude/agents/foo.md, polluted .gitignore)',
    tier3Artifact: 'PRD for a feature traced to the repo issue tracker (product-manager → researcher → architect → engineer)',
    peer: 'B',
  },
  c: {
    id: 'c',
    title: 'Research project',
    workspacePreset: 'research',
    reportFile: 'scenario-c-research-corpus.md',
    fixture: 'three primary-source PDFs + five markdown notes dropped into inbox/',
    tier3Artifact: 'evidence brief synthesizing the corpus (researcher → cx-evaluator)',
    peer: 'C',
  },
};

export const TIERS = [
  { n: 1, title: 'Install + Init UX (owner observation)' },
  { n: 2, title: 'Command sweep (all public + internal)' },
  { n: 3, title: 'Quality-bar artifact (real LLM)' },
  { n: 4, title: 'Loops, skills, specialists, templates' },
  { n: 5, title: 'Documentation parity' },
  { n: 6, title: 'Peer comparison (owner-review lens)' },
  { n: 7, title: 'Invocable by other applications' },
];

function parseArgs(argv) {
  const args = { skeleton: false, scenario: 'all', reportDir: DEFAULT_REPORT_DIR };
  for (const a of argv) {
    if (a === '--skeleton') args.skeleton = true;
    else if (a.startsWith('--scenario=')) args.scenario = a.slice('--scenario='.length).toLowerCase();
    else if (a.startsWith('--report-dir=')) args.reportDir = resolve(a.slice('--report-dir='.length));
  }
  return args;
}

// Generated reports are committed and inspectable, so they carry a provenance
// header block: their path, purpose, and the regenerate instruction. The block
// also satisfies the comment policy's file-header requirement for tracked
// markdown under tests/.

function mdHeader(relPath, purpose, summaryLines) {
  return ['<!--', `${relPath} — ${purpose}`, '', ...summaryLines, '-->', ''].join('\n');
}

// The skeleton report pins the verified facts the live tiers will fill in:
// the real command counts from the catalog, the fixed verdict grid, the tier
// list, and the peer row for this scenario. Numbers trace to source — the
// catalog is read at render time, not hardcoded.

function renderSkeletonReport(scenario, counts) {
  const peer = PEER_ROWS.find((r) => r.scenario === scenario.peer);
  const lines = [];
  lines.push(mdHeader(
    `tests/e2e/reports/${scenario.reportFile}`,
    `Scenario ${scenario.id.toUpperCase()} (${scenario.title}) E2E owner-review report.`,
    [
      'Generated by tests/e2e/runner.mjs. Regenerate with the runner rather than editing here.',
      'Sections map to the seven validation tiers; verdicts use the owner-verdict grid.',
    ],
  ));
  lines.push(`# Scenario ${scenario.id.toUpperCase()} — ${scenario.title}`);
  lines.push('');
  lines.push('> **Status: SKELETON.** Scaffolding only — no fixtures built, no commands run, no model calls made. Generated by `tests/e2e/runner.mjs --skeleton` for the Sequencing-step-1 owner checkpoint.');
  lines.push('');
  lines.push('## Scenario definition');
  lines.push('');
  lines.push(`- **Profile:** \`${scenario.profile}\``);
  lines.push(`- **Fixture:** ${scenario.fixture}`);
  lines.push(`- **Tier-3 artifact:** ${scenario.tier3Artifact}`);
  lines.push(`- **Sterile env:** dedicated tmpdir, isolated \`HOME\` + \`CONSTRUCT_HOME_OVERRIDE\`, own \`git init\`.`);
  lines.push('');
  lines.push('## Verified inputs (read from source at render time)');
  lines.push('');
  lines.push(`- Public commands: **${counts.public.length}** · Internal commands: **${counts.internal.length}** · Total: **${counts.all.length}** (from \`lib/cli-commands.mjs\`).`);
  lines.push(`- Embedded contract version: **${CONTRACT_VERSION}** (from \`lib/embedded-contract/contract-version.mjs\`).`);
  lines.push(`- Internal commands (must stay hidden from \`--help\` and completion): ${counts.internal.map((c) => `\`${c.name}\``).join(', ')}.`);
  lines.push('');
  lines.push('## Tiers');
  lines.push('');
  for (const t of TIERS) {
    lines.push(`### Tier ${t.n} — ${t.title}`);
    lines.push('');
    lines.push('_Pending execution._');
    lines.push('');
  }
  lines.push('## Owner-review verdict grid');
  lines.push('');
  lines.push(`| Subject | ${VERDICT_COLUMNS.join(' | ')} |`);
  lines.push(`| --- | ${VERDICT_COLUMNS.map(() => '---').join(' | ')} |`);
  lines.push('| _(rows added per command / artifact / surface during execution)_ | | | | | |');
  lines.push('');
  if (peer) {
    lines.push('## Tier-6 peer');
    lines.push('');
    lines.push(`- **Dimension:** ${peer.dimension}`);
    lines.push(`- **Peer:** ${peer.peer}`);
    lines.push(`- **Primary sources (access dates stamped at fetch time):**`);
    for (const s of peer.sources) lines.push(`  - ${s.url}`);
    lines.push('');
  }
  return lines.join('\n');
}

function renderSkeletonSummary(counts) {
  const lines = [];
  lines.push(mdHeader(
    'tests/e2e/reports/summary.md',
    'Cross-scenario synthesis for the Construct E2E owner-review pass.',
    [
      'Generated by tests/e2e/runner.mjs. Regenerate with the runner rather than editing here.',
      'Aggregates the three scenario reports into one verdict and a bd-issue index.',
    ],
  ));
  lines.push('# Construct E2E owner-review — cross-scenario summary');
  lines.push('');
  lines.push('> **Status: SKELETON.** Generated by `tests/e2e/runner.mjs --skeleton`.');
  lines.push('');
  lines.push('## Scope');
  lines.push('');
  lines.push(`- **${counts.public.length}** public + **${counts.internal.length}** internal commands swept per scenario (Tier 2).`);
  lines.push(`- **3** scenarios × **7** tiers.`);
  lines.push(`- Embedded contract **${CONTRACT_VERSION}** probed across 5 surfaces (Tier 7).`);
  lines.push('');
  lines.push('## Scenarios');
  lines.push('');
  for (const s of Object.values(SCENARIOS)) lines.push(`- **${s.id.toUpperCase()}** — ${s.title} (\`${s.profile}\`) → \`${s.reportFile}\``);
  lines.push('');
  lines.push('## Pending');
  lines.push('');
  lines.push('- Highest-leverage improvement (CLI-facing and embedder-facing) — named after execution.');
  lines.push('- bd issue index — populated as failures surface.');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const counts = enumerateCommands();
  mkdirSync(args.reportDir, { recursive: true });

  if (!args.skeleton) {
    process.stderr.write('[e2e] only --skeleton mode is wired in this commit. Re-run with --skeleton.\n');
    process.exit(2);
  }

  const targets = args.scenario === 'all' ? Object.values(SCENARIOS) : [SCENARIOS[args.scenario]].filter(Boolean);
  if (targets.length === 0) {
    process.stderr.write(`[e2e] unknown scenario "${args.scenario}". Use a|b|c|all.\n`);
    process.exit(2);
  }

  for (const scenario of targets) {
    const report = renderSkeletonReport(scenario, counts);
    const out = join(args.reportDir, scenario.reportFile);
    writeFileSync(out, report + '\n');
    process.stdout.write(`[e2e] wrote ${out}\n`);
  }

  const summaryOut = join(args.reportDir, 'summary.md');
  writeFileSync(summaryOut, renderSkeletonSummary(counts) + '\n');
  process.stdout.write(`[e2e] wrote ${summaryOut}\n`);
  process.stdout.write(`[e2e] skeleton complete — ${counts.public.length} public + ${counts.internal.length} internal commands, contract ${CONTRACT_VERSION}, repo ${REPO_ROOT}\n`);
}

main().catch((err) => {
  process.stderr.write(`[e2e] runner failed: ${err.stack || err.message}\n`);
  process.exit(1);
});
