/**
 * tests/sync-agents-header.test.mjs — verify sync-agents.mjs emits canonical headers.
 *
 * Checks that generated Claude Code agent markdown files contain the required
 * "Generated by construct sync" banner produced by generatedMarkdownNote.
 */

import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { spawnSync } from 'node:child_process';

const ROOT_DIR = path.resolve(import.meta.dirname, '..');
const HOME = os.homedir();

test('generatedMarkdownNote contains canonical Generated header', async () => {
  const { default: url } = await import('node:url');
  const src = fs.readFileSync(path.join(ROOT_DIR, 'sync-agents.mjs'), 'utf8');

  assert.ok(
    src.includes('Generated by construct sync from agents/registry.json'),
    'sync-agents.mjs must contain canonical "Generated by construct sync" text in generatedMarkdownNote'
  );
  assert.ok(
    src.includes('Do not edit this file directly'),
    'sync-agents.mjs must include the "Do not edit" warning'
  );
  assert.ok(
    src.includes('Regenerate: construct sync'),
    'sync-agents.mjs must include the regeneration instruction'
  );
});

test('generatedMarkdownNote uses HTML comment wrapper', () => {
  const src = fs.readFileSync(path.join(ROOT_DIR, 'sync-agents.mjs'), 'utf8');
  const match = src.match(/const generatedMarkdownNote\s*=\s*([\s\S]*?)(?:;|\n\n)/);
  assert.ok(match, 'should find generatedMarkdownNote definition');
  assert.ok(match[1].includes("'<!--'") || match[1].includes('"<!--"') || match[1].includes('<!--'),
    'generatedMarkdownNote should include an HTML comment open tag');
});

test('Codex agent TOML includes required top-level name field', () => {
  const src = fs.readFileSync(path.join(ROOT_DIR, 'sync-agents.mjs'), 'utf8');
  assert.match(
    src,
    /function codexAgentToml[\s\S]*name = \$\{tomlString\(name\)\}/,
    'codexAgentToml must emit a non-empty name field for Codex role loading'
  );
});

test('Codex agent TOML includes required top-level description field', () => {
  const src = fs.readFileSync(path.join(ROOT_DIR, 'sync-agents.mjs'), 'utf8');
  assert.match(
    src,
    /function codexAgentToml[\s\S]*description = \$\{tomlString\(entry\.description\)\}/,
    'codexAgentToml must emit a non-empty description field for Codex role loading'
  );
});
