/**
 * lib/mcp/tool-safety.mjs — per-tool safety classification for the MCP catalog.
 *
 * One entry per tool name in lib/mcp/server.mjs's ALL_TOOL_DEFS (plus the `call`
 * gateway). `class` is the host-facing risk tier; `filesystem`/`network`/`process`
 * name which resource classes the tool can touch, derived from each tool's own
 * description and input schema. withSafetyEnvelope (server.mjs) throws if a tool
 * is missing here, so a newly added tool cannot ship without classification.
 */

const READ = 'read';
const WRITE = 'write';
const DESTRUCTIVE = 'destructive';

export const DEFAULT_OUTPUT_SCHEMA = Object.freeze({ type: 'object' });

export const TOOL_SAFETY = Object.freeze({
  agent_health: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  summarize_diff: { class: READ, filesystem: 'read', network: 'none', process: 'spawn' },
  scan_file: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  extract_document_text: { class: READ, filesystem: 'read', network: 'none', process: 'spawn' },
  ingest_document: { class: WRITE, filesystem: 'write', network: 'none', process: 'spawn' },
  infer_document_schema: { class: WRITE, filesystem: 'write', network: 'fetch', process: 'spawn' },
  list_schema_artifacts: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  storage_status: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  storage_sync: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  storage_reset: { class: DESTRUCTIVE, filesystem: 'write', network: 'none', process: 'none' },
  delete_ingested_artifacts: { class: DESTRUCTIVE, filesystem: 'write', network: 'none', process: 'none' },
  project_context: { class: READ, filesystem: 'read', network: 'none', process: 'spawn' },
  get_skill: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  orchestration_policy: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  list_skills: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  worker_run: { class: WRITE, filesystem: 'write', network: 'fetch', process: 'spawn' },
  broker_check: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  find_tool: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  get_template: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  list_templates: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  search_skills: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  list_worker_profiles: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  get_worker_profile: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  list_procedures: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  get_procedure: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  list_capabilities: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  get_capability: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  list_policies: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  get_policy: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  suggest_skills: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  construct_trace: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  construct_score: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  construct_trace_update: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  session_list: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  session_load: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  session_search: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  session_save: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  memory_search: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  memory_add_observations: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  memory_create_entities: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  memory_recent: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  rovo_search: { class: READ, filesystem: 'none', network: 'fetch', process: 'none' },
  efficiency_snapshot: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  session_usage: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  provider_fetch: { class: WRITE, filesystem: 'write', network: 'fetch', process: 'none' },
  provider_write: { class: DESTRUCTIVE, filesystem: 'write', network: 'fetch', process: 'none' },
  workspace_preset_show: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workspace_preset_list: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workspace_preset_drafts: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workspace_preset_health: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  outcomes_summary: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  outcomes_record: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  knowledge_add: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  workspace_preset_create: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  workspace_preset_archive: { class: DESTRUCTIVE, filesystem: 'write', network: 'none', process: 'none' },
  sandbox_list: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  knowledge_graph_ask: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  learning_status: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  document_export: { class: WRITE, filesystem: 'write', network: 'none', process: 'spawn' },
  publish_detect: { class: READ, filesystem: 'read', network: 'none', process: 'spawn' },
  publish_run: { class: WRITE, filesystem: 'write', network: 'none', process: 'spawn' },
  knowledge_search: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workflow_init: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  workflow_add_task: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  workflow_update_task: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  workflow_needs_main_input: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  workflow_validate: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workflow_status: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workflow_contract_validate: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  workflow_import_plan: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  artifact_workflow: { class: WRITE, filesystem: 'write', network: 'none', process: 'spawn' },
  author_artifact: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  model_resolve: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  triage_recommend: { class: READ, filesystem: 'read', network: 'none', process: 'spawn' },
  procedure_invoke: { class: WRITE, filesystem: 'write', network: 'none', process: 'spawn' },
  capability_describe: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  construct_execution_resolve: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  orchestration_run: { class: WRITE, filesystem: 'write', network: 'fetch', process: 'none' },
  web_search: { class: READ, filesystem: 'none', network: 'fetch', process: 'none' },
  orchestration_status: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  orchestration_cancel: { class: WRITE, filesystem: 'write', network: 'none', process: 'none' },
  orchestration_readiness: { class: READ, filesystem: 'read', network: 'none', process: 'none' },
  call: { class: DESTRUCTIVE, filesystem: 'write', network: 'fetch', process: 'spawn' },
});
