/**
 * project-parity.functional.test.mjs — project-scoped adapter parity checks.
 *
 * Verifies checkProjectParity detects missing/stale Cursor and VS Code adapters
 * in a Construct-managed fixture project.
 */
import test from 'node:test';
import assert from 'node:assert';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { checkProjectParity } from '../../lib/parity.mjs';

const ROOT = process.cwd();

test('skips non-Construct projects', () => {
  const dir = mkdtempSync(join(tmpdir(), 'cx-parity-skip-'));
  try {
    const r = checkProjectParity({ rootDir: ROOT, projectDir: dir });
    assert.equal(r.skipped, true);
    assert.equal(r.ok, true);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('reports absent project adapters when .cx exists', () => {
  const dir = mkdtempSync(join(tmpdir(), 'cx-parity-miss-'));
  try {
    mkdirSync(join(dir, '.cx'));
    const r = checkProjectParity({ rootDir: ROOT, projectDir: dir });
    assert.equal(r.skipped, false);
    const absent = r.surfaces.filter((s) => s.status === 'absent');
    assert.ok(absent.length >= 1, 'expected at least one absent adapter surface');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test('ok when construct agent and cursor rule present', () => {
  const dir = mkdtempSync(join(tmpdir(), 'cx-parity-ok-'));
  try {
    mkdirSync(join(dir, '.cx'));
    mkdirSync(join(dir, '.claude', 'agents'), { recursive: true });
    writeFileSync(join(dir, '.claude', 'agents', 'construct.md'), '# construct');
    mkdirSync(join(dir, '.cursor', 'rules'), { recursive: true });
    writeFileSync(
      join(dir, '.cursor', 'rules', 'construct.mdc'),
      '---\ndescription: test\n---\n\n<!-- Generated by construct sync -->\n',
    );
    const r = checkProjectParity({ rootDir: ROOT, projectDir: dir });
    const claude = r.surfaces.find((s) => s.surface === 'claude');
    const rules = r.surfaces.find((s) => s.kind === 'rules');
    assert.equal(claude?.status, 'ok');
    assert.equal(rules?.status, 'ok');
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
