/**
 * tests/functional/reconcile-legacy-skills.functional.test.mjs
 *
 * Functional coverage for ADR-0027 / Item 12 (state reconciliation framework)
 * and Item 10's legacy-skills-cleanup task. Each test isolates HOME under a
 * tmpdir (CX_HOME_OVERRIDE + HOME) so the real ~/.agents/skills is untouched.
 *
 * Cases:
 *   1) Empty machine — detect() reports no repair needed, apply() is no-op.
 *   2) Stale Construct shape only — detect() reports needsRepair, apply()
 *      removes every file and prunes the directory tree.
 *   3) Mixed: stale Construct files + a foreign skill file by a different
 *      author — apply() removes only the Construct-shaped stale files,
 *      preserves the foreign one, prunes only empty branches.
 *   4) Stale shape but mtime drifted far past updated_at (user-edit signal)
 *      — apply() preserves the file.
 *   5) Stamp file is written under the overridden HOME and replays
 *      idempotently (second detect() returns no-op).
 */

import { mkdtempSync, mkdirSync, writeFileSync, existsSync, utimesSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import test from 'node:test';
import { rmTmpDir } from '../helpers/cleanup.mjs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const RECONCILE_MOD = join(REPO_ROOT, 'lib', 'reconcile', 'index.mjs');

const STALE_UPDATED_AT = '2026-06-04T01:45:44.289Z';
const STALE_UPDATED_AT_MS = Date.parse(STALE_UPDATED_AT);

const STALE_FRONTMATTER = `---
cx_doc_id: 019e904e-ce61-7d81-80f1-655d661020e7
created_at: ${STALE_UPDATED_AT}
updated_at: ${STALE_UPDATED_AT}
generator: construct/sync-specialists
body_hash: sha256:1bf2ed0c32121f54dfa43bff79671e7a916d5909e3b393df3288824f312af838
---
# Generated by construct sync

Body content for a Construct-shaped stale SKILL.md.
`;

const CURRENT_FRONTMATTER = `---
name: strategy-competitive-landscape
description: Use when the team needs a structured read on market positioning before committing direction.
---

# Competitive Landscape Analysis
`;

const FOREIGN_FRONTMATTER = `---
name: third-party-skill
description: Authored by a tool that is not Construct; reconciler must leave it alone.
---

# Foreign skill body
`;

function writeSkill(homeOverride, rel, content, opts = {}) {
  const full = join(homeOverride, '.agents', 'skills', rel, 'SKILL.md');
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  if (opts.mtimeMs !== undefined) {
    const sec = opts.mtimeMs / 1000;
    utimesSync(full, sec, sec);
  }
  return full;
}

async function freshReconcileModule() {
  // Fresh import each test — module-level caches in the registry are
  // negligible, but the CX_HOME_OVERRIDE env var is read at call time so
  // re-import is not strictly required. We re-import to keep tests
  // independent of any future module-level caching.
  const ts = Date.now();
  return import(`${pathToFileURL(RECONCILE_MOD).href}?ts=${ts}`);
}

// cwd is moved into the isolated (non-project) home so the project-scoped auto
// reconciliations registered alongside legacy-skills-cleanup stay no-ops and
// never mutate the real working tree during runAutoReconciliations().

function withIsolatedHome(fn) {
  const home = mkdtempSync(join(tmpdir(), 'cx-reconcile-'));
  const prev = {
    HOME: process.env.HOME,
    CX_HOME_OVERRIDE: process.env.CX_HOME_OVERRIDE,
    cwd: process.cwd(),
  };
  process.env.HOME = home;
  process.env.CX_HOME_OVERRIDE = home;
  process.chdir(home);
  return Promise.resolve(fn(home)).finally(() => {
    process.chdir(prev.cwd);
    process.env.HOME = prev.HOME;
    if (prev.CX_HOME_OVERRIDE === undefined) delete process.env.CX_HOME_OVERRIDE;
    else process.env.CX_HOME_OVERRIDE = prev.CX_HOME_OVERRIDE;
    rmTmpDir(home);
  });
}

test('reconcile/legacy-skills: empty machine — no-op', async () => {
  await withIsolatedHome(async () => {
    const { runAutoReconciliations, listReconciliations } = await freshReconcileModule();
    const before = await listReconciliations();
    const task = before.find((t) => t.id === 'legacy-skills-cleanup');
    assert.ok(task, 'task is registered');
    assert.equal(task.needsRepair, false, 'no repair on empty machine');
    const { applied, skipped } = await runAutoReconciliations();
    assert.equal(applied.length, 0);
    assert.ok(skipped.some((s) => s.id === 'legacy-skills-cleanup' && s.reason === 'no-op'));
  });
});

test('reconcile/legacy-skills: stale-only — removes all + prunes', async () => {
  await withIsolatedHome(async (home) => {
    writeSkill(home, 'strategy/competitive-landscape', STALE_FRONTMATTER, { mtimeMs: STALE_UPDATED_AT_MS });
    writeSkill(home, 'development/typescript', STALE_FRONTMATTER, { mtimeMs: STALE_UPDATED_AT_MS });
    writeSkill(home, 'operating/incident-response', STALE_FRONTMATTER, { mtimeMs: STALE_UPDATED_AT_MS });
    const { runAutoReconciliations, listReconciliations } = await freshReconcileModule();
    const beforeList = await listReconciliations();
    const beforeTask = beforeList.find((t) => t.id === 'legacy-skills-cleanup');
    assert.equal(beforeTask.needsRepair, true);
    const { applied } = await runAutoReconciliations();
    const entry = applied.find((a) => a.id === 'legacy-skills-cleanup');
    assert.ok(entry, 'reconciliation ran');
    assert.match(entry.summary, /Removed 3 stale SKILL.md/);
    assert.equal(existsSync(join(home, '.agents', 'skills')), false, 'skills root pruned');
    const afterList = await listReconciliations();
    const afterTask = afterList.find((t) => t.id === 'legacy-skills-cleanup');
    assert.equal(afterTask.needsRepair, false, 'second detect is no-op');
    assert.equal(afterTask.previouslyApplied, true, 'stamp was written');
  });
});

test('reconcile/legacy-skills: mixed — leaves foreign + current alone', async () => {
  await withIsolatedHome(async (home) => {
    const stale = writeSkill(home, 'strategy/competitive-landscape', STALE_FRONTMATTER, { mtimeMs: STALE_UPDATED_AT_MS });
    const foreign = writeSkill(home, 'third-party/widget', FOREIGN_FRONTMATTER);
    const current = writeSkill(home, 'development/typescript', CURRENT_FRONTMATTER);
    const { runAutoReconciliations } = await freshReconcileModule();
    await runAutoReconciliations();
    assert.equal(existsSync(stale), false, 'stale file removed');
    assert.equal(existsSync(foreign), true, 'foreign file preserved');
    assert.equal(existsSync(current), true, 'current Construct file preserved');
  });
});

test('reconcile/legacy-skills: user-edited stale — preserved (mtime past updated_at)', async () => {
  await withIsolatedHome(async (home) => {
    const futureMtimeMs = Date.parse('2026-06-04T01:45:44.289Z') + (30 * 60 * 1000);
    const file = writeSkill(home, 'strategy/competitive-landscape', STALE_FRONTMATTER, { mtimeMs: futureMtimeMs });
    const { runAutoReconciliations, listReconciliations } = await freshReconcileModule();
    const { applied, skipped } = await runAutoReconciliations();
    const reconcileEntry = applied.find((a) => a.id === 'legacy-skills-cleanup');
    const skippedEntry = skipped.find((a) => a.id === 'legacy-skills-cleanup');
    // The single file is user-edited and not safe to remove, so the task
    // reports no-op rather than applying.
    assert.equal(!!reconcileEntry, false, 'no entry applied');
    assert.ok(skippedEntry && skippedEntry.reason === 'no-op', 'reported no-op when only file is user-edited');
    assert.equal(existsSync(file), true, 'user-edited file preserved');
    const list = await listReconciliations();
    const task = list.find((t) => t.id === 'legacy-skills-cleanup');
    assert.match(task.summary || '', /user-edited stale: 1/);
  });
});

test('reconcile/legacy-skills: stamp file written under overridden HOME', async () => {
  await withIsolatedHome(async (home) => {
    writeSkill(home, 'strategy/competitive-landscape', STALE_FRONTMATTER, { mtimeMs: STALE_UPDATED_AT_MS });
    const { runAutoReconciliations, reconcileStampPath } = await freshReconcileModule();
    await runAutoReconciliations();
    const stamp = reconcileStampPath();
    assert.ok(stamp.startsWith(home), `stamp path is under HOME override: ${stamp}`);
    assert.equal(existsSync(stamp), true, 'stamp file exists');
    const parsed = JSON.parse(readFileSync(stamp, 'utf8'));
    assert.ok(parsed.applied['legacy-skills-cleanup'], 'task recorded in stamp');
    assert.ok(parsed.applied['legacy-skills-cleanup'].at, 'timestamp present');
  });
});
