/**
 * Performance.tsx — agent performance reviews + operator feedback.
 *
 * Reads ~/.cx/performance-reviews/*.json (auto-generated by the
 * session-optimize hook end-of-session). Each review carries per-agent
 * stats: invocations, avgScore, trend, failureRate, status. Operator
 * can enter feedback per agent which writes to .cx/feedback/ and
 * appends an audit entry — this becomes the seed for proposed persona
 * updates that the construct persona can review and apply.
 */
import { useEffect, useState } from 'react';

type AgentStat = {
  name: string;
  invocations: number;
  scoredInvocations: number;
  avgScore: number;
  trend: string;
  failureRate: number;
  status: string;
  lowScoreTraces?: string[];
  reasoning?: string;
};
type Review = {
  filename: string;
  generated: string;
  period: { from: string; to: string; days: number };
  agentStats: AgentStat[];
};

function statusPip(status: string): string {
  if (status === 'healthy') return 'pip pip-healthy';
  if (status === 'needs_attention') return 'pip pip-degraded';
  if (status === 'failing' || status === 'broken') return 'pip pip-down';
  return 'pip';
}

export default function Performance() {
  const [reviews, setReviews] = useState<Review[]>([]);
  const [mockFiltered, setMockFiltered] = useState(0);
  const [generatorImplemented, setGeneratorImplemented] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [feedbackFor, setFeedbackFor] = useState<string | null>(null);
  const [feedbackText, setFeedbackText] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/performance/reviews')
      .then((r) => r.json())
      .then((j) => {
        if (j.error) setError(j.error);
        else {
          setReviews(j.reviews || []);
          setMockFiltered(j.mockFiltered || 0);
          setGeneratorImplemented(j.generatorImplemented !== false);
        }
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  async function submitFeedback(agent: string) {
    setSubmitting(true);
    try {
      const r = await fetch('/api/performance/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ agent, text: feedbackText }),
      });
      const j = await r.json();
      if (!r.ok) throw new Error(j.error || `HTTP ${r.status}`);
      setSubmitted(`Feedback saved to .cx/feedback/${j.filename}`);
      setFeedbackText('');
      setFeedbackFor(null);
    } catch (e: any) {
      setSubmitted(`Error: ${e.message}`);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="max-w-5xl space-y-6">
      <header>
        <p className="text-text-dim text-xs uppercase tracking-wider mb-1">Page</p>
        <h1 className="text-3xl font-semibold tracking-tight">Performance reviews</h1>
        <p className="text-text-muted text-sm mt-2">
          Auto-generated end-of-session summaries from <code className="px-1 py-0.5 bg-bg-muted rounded">~/.cx/performance-reviews/</code>. Each agent carries invocations + avg-score + trend + status. Add feedback to seed proposed prompt updates.
        </p>
      </header>

      {error && (
        <div className="card" style={{ borderColor: 'var(--status-down)' }}>
          <p className="text-sm">{error}</p>
        </div>
      )}

      {submitted && (
        <div className="card" style={{ borderColor: 'var(--status-healthy)' }}>
          <p className="text-sm">{submitted}</p>
        </div>
      )}

      {loading && <p className="text-sm text-text-dim">Loading reviews…</p>}

      {!loading && reviews.length === 0 && !error && (
        <section className="card">
          <h2 className="text-lg font-semibold mb-2">No performance reviews yet</h2>
          <p className="text-sm text-text-muted">
            Run <code className="px-1 py-0.5 bg-bg-muted rounded">construct review run</code> to generate the first review from your cost ledger + Langfuse generations. The Stop hook also runs this every 24 hours automatically once the hooks are installed.
          </p>
          {mockFiltered > 0 && (
            <p className="text-xs text-text-dim mt-3">
              Filtered out {mockFiltered} mock fixture file{mockFiltered === 1 ? '' : 's'} (<code className="px-1 py-0.5 bg-bg-muted rounded">test-*-mock.json</code>) in <code className="px-1 py-0.5 bg-bg-muted rounded">~/.cx/performance-reviews/</code> — those are test seeds, not real reviews.
            </p>
          )}
        </section>
      )}

      {reviews.map((review) => (
        <section key={review.filename} className="card space-y-4">
          <header className="flex items-start justify-between flex-wrap gap-3">
            <div>
              <h2 className="text-lg font-semibold">Review {new Date(review.generated).toLocaleDateString()}</h2>
              <p className="text-xs text-text-dim mt-1">
                Period: {review.period.days} days · {new Date(review.period.from).toLocaleDateString()} → {new Date(review.period.to).toLocaleDateString()}
              </p>
            </div>
            <div className="text-xs text-text-dim font-mono">{review.filename}</div>
          </header>

          <table className="w-full text-sm">
            <thead className="text-xs uppercase tracking-wider text-text-dim">
              <tr>
                <th className="text-left font-normal pb-2">Agent</th>
                <th className="text-right font-normal pb-2">Invocations</th>
                <th className="text-right font-normal pb-2">Avg score</th>
                <th className="text-right font-normal pb-2">Fail rate</th>
                <th className="text-left font-normal pb-2 pl-3">Trend</th>
                <th className="text-left font-normal pb-2 pl-3">Status</th>
                <th className="text-right font-normal pb-2"></th>
              </tr>
            </thead>
            <tbody>
              {review.agentStats?.map((a) => (
                <>
                  <tr key={a.name} className="border-t border-border align-top">
                    <td className="py-2 font-mono text-xs">{a.name}</td>
                    <td className="py-2 text-right">{a.invocations}</td>
                    <td className="py-2 text-right">{a.avgScore?.toFixed(2)}</td>
                    <td className="py-2 text-right">{Math.round((a.failureRate || 0) * 100)}%</td>
                    <td className="py-2 pl-3 text-xs">{a.trend}</td>
                    <td className="py-2 pl-3">
                      <span className={statusPip(a.status)}>
                        <span aria-hidden="true">
                          {a.status === 'healthy' ? '✓' : a.status === 'needs_attention' ? '!' : '✕'}
                        </span>
                        {a.status}
                      </span>
                    </td>
                    <td className="py-2 text-right">
                      <button
                        type="button"
                        onClick={() => { setFeedbackFor(a.name); setFeedbackText(''); }}
                        className="btn text-xs"
                      >
                        Feedback
                      </button>
                    </td>
                  </tr>
                  {feedbackFor === a.name && (
                    <tr key={`${a.name}-feedback`} className="bg-bg-muted">
                      <td colSpan={7} className="p-3">
                        <label className="block text-xs uppercase tracking-wider text-text-dim mb-2">
                          Feedback for {a.name}
                        </label>
                        <textarea
                          value={feedbackText}
                          onChange={(e) => setFeedbackText(e.target.value)}
                          rows={4}
                          placeholder="Describe what should change about this agent's behavior. The feedback seeds proposed prompt updates."
                          className="w-full p-2 border border-border rounded bg-surface text-sm"
                        />
                        <div className="flex items-center gap-2 mt-2">
                          <button
                            type="button"
                            onClick={() => submitFeedback(a.name)}
                            disabled={!feedbackText.trim() || submitting}
                            className="btn btn-primary text-xs disabled:opacity-50"
                          >
                            {submitting ? 'Saving…' : 'Save feedback'}
                          </button>
                          <button
                            type="button"
                            onClick={() => { setFeedbackFor(null); setFeedbackText(''); }}
                            className="btn text-xs"
                          >
                            Cancel
                          </button>
                        </div>
                      </td>
                    </tr>
                  )}
                </>
              ))}
            </tbody>
          </table>
        </section>
      ))}
    </div>
  );
}
