#!/usr/bin/env node
/**
 * lib/hooks/pre-compact.mjs — Pre-compact hook — prepares context summary before compaction runs.
 *
 * Runs before context compaction. Writes a structured summary of context state and pending tasks to preserve continuity across the compaction boundary.
 *
 * Manual sections in context.md (any heading not in AUTO_SECTION_NAMES) are
 * detected, preserved verbatim, and re-appended after the auto-generated
 * sections so that hand-written decisions, active-work notes, and architecture
 * context survive every compaction cycle.
 *
 * @p95ms 100
 * @maxBlockingScope PreCompact
 *
 * @lifecycle PreCompact
 * @matcher  *
 * @exits 0 = pass
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { writeContextState, contextMarkdownPath, contextJsonPath } from '../context-state.mjs';
import { flushReadTrackerDeltas } from '../read-tracker-store.mjs';
import { doctorRoot } from '../config/xdg.mjs';
import { projectConfigDir } from '../config-dir.mjs';
import { isMainModule } from '../roots.mjs';
import { homeDir } from '../paths.mjs';

// Section headings that are auto-generated by this hook. Any other heading in
// the existing context.md is treated as manually authored and preserved.
// Exported so tests exercise the real set instead of a re-pasted copy.
export const AUTO_SECTION_NAMES = new Set([
  'what was in progress',
  'files changed this session',
  'decisions captured',
  'pending todos',
  'session efficiency snapshot',
  'open issues',
  'session context',
]);

/**
 * Parse a markdown string into `[{heading, level, body}]` sections.
 * Returns an empty array for empty/missing input.
 */
export function parseSections(md) {
  if (!md) return [];
  const lines = md.split('\n');
  const sections = [];
  let current = null;
  for (const line of lines) {
    const hm = line.match(/^(#{1,6})\s+(.+)$/);
    if (hm) {
      if (current) sections.push(current);
      current = { heading: line, level: hm[1].length, title: hm[2].trim(), body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) sections.push(current);
  return sections;
}

/**
 * Extract sections from an existing context.md that were NOT auto-generated.
 * Returns a markdown string (may be empty) to append after the auto content.
 */
export function extractManualSections(mdPath) {
  if (!existsSync(mdPath)) return '';
  let existing = '';
  try { existing = readFileSync(mdPath, 'utf8'); } catch { return ''; }
  const sections = parseSections(existing);
  const manual = sections.filter((s) => !AUTO_SECTION_NAMES.has(s.title.toLowerCase()));
  if (!manual.length) return '';
  return manual
    .map((s) => [s.heading, ...s.body].join('\n').trimEnd())
    .join('\n\n') + '\n';
}

/**
 * Merge non-empty arrays from existing context.json into the new state to
 * prevent the hook from discarding decisions/filesChanged captured manually.
 */
export function mergeExistingJson(jsonPath, newState) {
  if (!existsSync(jsonPath)) return newState;
  let existing = {};
  try { existing = JSON.parse(readFileSync(jsonPath, 'utf8')); } catch { return newState; }
  const merged = { ...newState };
  for (const key of ['decisions', 'filesChanged', 'pendingTodos']) {
    if ((!merged[key] || !merged[key].length) && Array.isArray(existing[key]) && existing[key].length) {
      merged[key] = existing[key];
    }
  }
  return merged;
}

// Guard the hook body so importing this module for its exported helpers
// (tests, other tools) does not trigger the stdin read + process.exit(0).
// Mirrors the entrypoint guard already used in lib/hooks/rule-verifier.mjs.

if (isMainModule(import.meta.url)) {
  const machineStateRoot = doctorRoot(homeDir());
  let input = {};
  try { input = JSON.parse(readFileSync(0, 'utf8')); } catch { process.exit(0); }

  try { flushReadTrackerDeltas({ env: process.env }); } catch { /* best effort */ }

  const cwd = input?.cwd || process.cwd();
  const transcriptPath = input?.transcript_path || '';

  const filesChanged = [];
  const decisions = [];
  const pendingTodos = [];
  const warnFlagsPath = join(machineStateRoot, 'warn-flags.txt');
  const efficiencyPath = join(machineStateRoot, 'session-efficiency.json');
  let lastSummary = '';

  if (transcriptPath && existsSync(transcriptPath)) {
    try {
      const transcriptRaw = readFileSync(transcriptPath, 'utf8');
      let transcript;
      try {
        transcript = JSON.parse(transcriptRaw);
      } catch {
        transcript = transcriptRaw
          .split('\n')
          .filter(Boolean)
          .map((line) => {
            try { return JSON.parse(line); } catch { return null; }
          })
          .filter(Boolean);
      }
      const messages = Array.isArray(transcript) ? transcript : (transcript.messages || []);
      const recent = messages.slice(-60);

      // Track the latest TodoWrite call to get current todo state
      let latestTodos = null;

      for (const msg of recent) {
        if (msg.role === 'tool' || msg.type === 'tool_result') continue;

        // Handle both array-of-blocks and plain-string content formats
        const blocks = Array.isArray(msg.content)
          ? msg.content
          : (typeof msg.content === 'string' ? [{ type: 'text', text: msg.content }] : []);

        for (const block of blocks) {
          if (block.type === 'tool_use' && (block.name === 'Write' || block.name === 'Edit')) {
            const fp = block.input?.file_path || block.input?.path || '';
            if (fp && !filesChanged.includes(fp)) filesChanged.push(fp);
          }
          if (block.type === 'tool_use' && block.name === 'TodoWrite') {
            const todos = block.input?.todos;
            if (Array.isArray(todos)) latestTodos = todos;
          }
          if (block.type === 'text' && msg.role === 'assistant') {
            const text = (block.text || '').trim();
            // Prefer the last substantive response (>80 chars) over short one-liners
            if (text.length > 80 || (!lastSummary && text.length > 0)) {
              lastSummary = text.slice(0, 400);
            }
            const decisionMatches = text.match(/(?:^|\n)(?:DECISION:|Decision:|\*\*Decision\*\*:)\s*([^\n]+)/g) || [];
            for (const match of decisionMatches) {
              const cleaned = match.replace(/^\n?/, '').replace(/^(?:DECISION:|Decision:|\*\*Decision\*\*:)\s*/, '').trim();
              if (cleaned && !decisions.includes(cleaned)) decisions.push(cleaned);
            }
          }
        }
      }

      // Extract pending/in_progress todos from latest TodoWrite
      if (latestTodos) {
        for (const todo of latestTodos) {
          if (todo.status === 'pending' || todo.status === 'in_progress') {
            pendingTodos.push(todo);
          }
        }
      }

    } catch { /* best effort */ }
  }

  const warnFlags = (() => {
    try { return readFileSync(warnFlagsPath, 'utf8').trim(); } catch { return ''; }
  })();

  const efficiencySummary = (() => {
    try {
      const stats = JSON.parse(readFileSync(efficiencyPath, 'utf8'));
      const parts = [
        `${stats.readCount || 0} reads`,
        `${stats.uniqueFileCount || 0} unique files`,
      ];
      if (stats.repeatedReadCount) parts.push(`${stats.repeatedReadCount} repeated reads`);
      if (stats.largeReadCount) parts.push(`${stats.largeReadCount} large reads`);
      if (stats.totalBytesRead) parts.push(`${Math.round(stats.totalBytesRead / 1024)} KB read`);
      return parts.join(' · ');
    } catch {
      return '';
    }
  })();

  const projectName = cwd.split('/').pop() || 'project';
  const date = new Date().toISOString().slice(0, 16).replace('T', ' ');

  const contextLines = [
    `# Session Context`,
    `Last saved: ${date}`,
    ``,
    `## What was in progress`,
    lastSummary || '(no summary available)',
    ``,
  ];

  if (filesChanged.length) {
    contextLines.push('## Files changed this session');
    for (const f of filesChanged.slice(0, 20)) contextLines.push(`- ${f}`);
    contextLines.push('');
  }

  if (decisions.length) {
    contextLines.push('## Decisions captured');
    for (const decision of decisions.slice(-10)) contextLines.push(`- ${decision}`);
    contextLines.push('');
  }

  if (pendingTodos.length) {
    contextLines.push('## Pending TODOs');
    for (const todo of pendingTodos) {
      const status = todo.status === 'in_progress' ? '[~]' : '[ ]';
      contextLines.push(`${status} ${todo.content || todo.title || todo.text || JSON.stringify(todo)}`);
    }
    contextLines.push('');
  }

  if (efficiencySummary) {
    contextLines.push('## Session efficiency snapshot');
    contextLines.push(efficiencySummary);
    contextLines.push('');
  }

  contextLines.push('## Open issues');
  contextLines.push(warnFlags || 'None');

  const content = contextLines.join('\n') + '\n';

  const projectCxDir = projectConfigDir(cwd);
  try { mkdirSync(projectCxDir, { recursive: true }); } catch { /* exists */ }

  // Preserve manually-written sections from the existing context.md.
  const projectMdPath = contextMarkdownPath(cwd);
  const manualSections = extractManualSections(projectMdPath);
  const finalContent = content + (manualSections ? '\n' + manualSections : '');

  const contextJson = {
    source: 'pre-compact',
    projectName,
    lastSummary,
    filesChanged: filesChanged.slice(0, 20),
    decisions: decisions.slice(-10),
    pendingTodos: pendingTodos.slice(0, 20),
    efficiencySummary,
    warnFlags: warnFlags || 'None',
  };

  // Merge non-empty arrays from the existing JSON so manually recorded state
  // is not silently dropped when the transcript scan finds nothing new.
  const mergedJson = mergeExistingJson(contextJsonPath(cwd), contextJson);

  try { writeContextState(cwd, { ...mergedJson, contextSummary: lastSummary }, { markdown: finalContent }); } catch { /* best effort */ }
  if (decisions.length) {
    const decisionsDir = join(projectCxDir, 'decisions');
    const slug = `${date.replace(/[^0-9]/g, '')}-session-decisions`;
    const decisionDoc = [
      '# Session Decisions',
      `Captured: ${date}`,
      '',
      '## Decisions',
      ...decisions.slice(-10).map((decision) => `- ${decision}`),
      '',
      '## Files changed',
      ...(filesChanged.length ? filesChanged.slice(0, 20).map((file) => `- ${file}`) : ['- None captured']),
      '',
    ].join('\n');
    try { mkdirSync(decisionsDir, { recursive: true }); } catch { /* exists */ }
    try { writeFileSync(join(decisionsDir, `${slug}.md`), decisionDoc); } catch { /* best effort */ }
  }

  const globalConfigDir = projectConfigDir(machineStateRoot);
  try { mkdirSync(globalConfigDir, { recursive: true }); } catch { /* exists */ }
  const globalMdPath = contextMarkdownPath(machineStateRoot);
  const globalManualSections = extractManualSections(globalMdPath);
  const globalFinalContent = content + (globalManualSections ? '\n' + globalManualSections : '');
  const globalMergedJson = mergeExistingJson(contextJsonPath(machineStateRoot), contextJson);
  try { writeContextState(machineStateRoot, { ...globalMergedJson, contextSummary: lastSummary }, { markdown: globalFinalContent }); } catch { /* best effort */ }

  process.exit(0);
}
