/**
 * lib/doc-verify.mjs — CLI handler for `construct doc verify`
 *
 * Walks one file or a directory tree, checks every stamped .md file for
 * body_hash integrity, and reports pass/fail/unstamped counts.
 *
 * Usage:
 *   construct doc verify [path]   [--json]
 *
 * Exit codes:
 *   0  all stamped files pass (or no stamped files found)
 *   1  one or more stamped files fail verification
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { verifyStamp, hasStamp } from './doc-stamp.mjs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

function walkMd(target) {
  const stat = fs.statSync(target);
  if (stat.isFile()) return target.endsWith('.md') ? [target] : [];
  const files = [];
  for (const entry of fs.readdirSync(target, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const full = path.join(target, entry.name);
    if (entry.isDirectory()) files.push(...walkMd(full));
    else if (entry.isFile() && entry.name.endsWith('.md')) files.push(full);
  }
  return files;
}

export function runDocVerifyCli(args) {
  const jsonMode = args.includes('--json');
  const targetArg = args.find(a => !a.startsWith('--'));
  const target = path.resolve(targetArg ?? process.cwd());

  if (!fs.existsSync(target)) {
    console.error(`construct doc verify: path not found: ${target}`);
    process.exit(1);
  }

  const files = walkMd(target);
  const results = { pass: [], fail: [], unstamped: [] };

  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    if (!hasStamp(content)) {
      results.unstamped.push(file);
      continue;
    }
    const v = verifyStamp(content);
    if (v.valid) results.pass.push({ file, id: v.id, created_at: v.created_at });
    else results.fail.push({ file, reason: v.reason, stored: v.stored, computed: v.computed });
  }

  if (jsonMode) {
    console.log(JSON.stringify(results, null, 2));
  } else {
    const rel = f => path.relative(process.cwd(), f);
    for (const r of results.fail) {
      console.log(`  FAIL  ${rel(r.file)}`);
      console.log(`        ${r.reason}`);
    }
    for (const r of results.pass) {
      console.log(`  ok    ${rel(r.file)}  [${r.id}]`);
    }
    if (results.unstamped.length) {
      console.log(`\n  ${results.unstamped.length} file(s) have no stamp (not generated by construct).`);
    }
    const summary = `\n  ${results.pass.length} passed, ${results.fail.length} failed, ${results.unstamped.length} unstamped`;
    console.log(summary);
  }

  if (results.fail.length > 0) process.exit(1);
}

/**
 * Install the prepare-commit-msg git hook into the nearest .git/hooks/ directory.
 */
export function runDocInstallHooksCli(_args) {
  const src = path.join(__dirname, 'git-hooks', 'prepare-commit-msg');
  if (!fs.existsSync(src)) {
    console.error(`construct doc install-hooks: hook source not found: ${src}`);
    process.exit(1);
  }

  // Walk up from cwd to find .git
  let dir = process.cwd();
  let gitDir = null;
  while (true) {
    const candidate = path.join(dir, '.git');
    if (fs.existsSync(candidate)) { gitDir = candidate; break; }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }

  if (!gitDir) {
    console.error('construct doc install-hooks: not inside a git repository');
    process.exit(1);
  }

  const hooksDir = path.join(gitDir, 'hooks');
  fs.mkdirSync(hooksDir, { recursive: true });
  const dest = path.join(hooksDir, 'prepare-commit-msg');

  if (fs.existsSync(dest)) {
    console.log(`  already installed: ${path.relative(process.cwd(), dest)}`);
    return;
  }

  fs.copyFileSync(src, dest);
  fs.chmodSync(dest, 0o755);
  console.log(`  installed: ${path.relative(process.cwd(), dest)}`);
  console.log('\n  Set CONSTRUCT_MODEL and CONSTRUCT_SESSION_ID in your shell or Construct config to populate trailers.');
}
