#!/usr/bin/env node
/**
 * lib/init-docs.mjs — stand up a documentation system for a project.
 *
 * This command is intentionally separate from `construct init`. It creates the
 * docs surface only: docs/README.md, docs/architecture.md, and selected lane
 * directories such as docs/prds/, docs/rfcs/, docs/adr/, docs/memos/, and
 * docs/runbooks/ with starter templates copied from Construct's template library.
 *
 * Usage:
 *   node lib/init-docs.mjs [target-path] [--yes] [--docs=prds,rfcs,adr]
 *   construct init-docs [path] [--yes] [--docs=prds,rfcs,adr]
 */

import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { fileURLToPath } from "node:url";

import { stampFrontmatter } from "./doc-stamp.mjs";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT_DIR = path.join(__dirname, "..");
const TEMPLATE_DIR = path.join(ROOT_DIR, "templates", "docs");

const args = process.argv.slice(2);
const skipInteractive = args.includes("--yes") || !process.stdin.isTTY;
const docsArg = args.find((arg) => arg.startsWith("--docs="));
const extrasArg = args.find((arg) => arg.startsWith("--extras="));
const targetArg = args.find((arg) => !arg.startsWith("--"));
const target = path.resolve(targetArg ?? process.cwd());

const created = [];
const skipped = [];

const DOC_LANES = {
  prds: {
    title: "PRDs",
    dir: "prds",
    description: "Product and capability requirement documents.",
    templates: ["prd.md", "meta-prd.md", "prd-business.md", "prd-platform.md", "prfaq.md"],
  },
  rfcs: {
    title: "RFCs",
    dir: "rfcs",
    description: "Architecture and implementation proposals that need review before a decision.",
    templates: ["rfc.md", "rfc-platform.md"],
  },
  adr: {
    title: "ADRs",
    dir: "adr",
    description: "Architecture decision records for decisions that have already been made.",
    templates: ["adr.md"],
  },
  memos: {
    title: "Memos",
    dir: "memos",
    description: "Decision memos and internal arguments for alignment and approval.",
    templates: ["memo.md"],
  },
  runbooks: {
    title: "Runbooks",
    dir: "runbooks",
    description: "Operational procedures, diagnostics, remediation, and escalation paths.",
    templates: ["runbook.md"],
  },
  briefs: {
    title: "Briefs",
    dir: "briefs",
    description: "Research, evidence, signal, and one-pager style documents.",
    templates: [
      "research-brief.md",
      "evidence-brief.md",
      "signal-brief.md",
      "one-pager.md",
      "customer-profile.md",
      "product-intelligence-report.md",
      "backlog-proposal.md",
    ],
  },
};

const DEFAULT_LANES = ["prds", "rfcs", "adr", "memos", "runbooks"];

function inferProjectName(targetPath) {
  const packageJsonPath = path.join(targetPath, "package.json");
  if (fs.existsSync(packageJsonPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
      return pkg.name || path.basename(targetPath);
    } catch {}
  }
  return path.basename(targetPath);
}

function parseCsvList(value) {
  return value
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean);
}

function normalizeCustomLaneName(name) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function writeIfMissing(filePath, content) {
  if (fs.existsSync(filePath)) {
    skipped.push(path.relative(target, filePath));
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const stamped = filePath.endsWith(".md")
    ? stampFrontmatter(content, { generator: "construct/init-docs" })
    : content;
  fs.writeFileSync(filePath, stamped, "utf8");
  created.push(path.relative(target, filePath));
}

function buildDocsReadme(projectName, selectedLanes) {
  const laneLines = selectedLanes.map((lane) => {
    const label = DOC_LANES[lane]?.title ?? titleCase(lane);
    const laneDir = DOC_LANES[lane]?.dir ?? lane;
    const desc = DOC_LANES[lane]?.description ?? "Custom documentation lane.";
    return `- [${label}](./${laneDir}/) — ${desc}`;
  });

  return `<!--
docs/README.md — documentation index and maintenance contract.

Generated by \`construct init-docs\`. Keep this file aligned with the actual doc
lanes in the repo. Update it when lanes are added, removed, or repurposed, and
prune stale links instead of letting the doc surface drift.
-->

# ${projectName} Documentation

> This docs surface is the canonical home for long-lived project documents such as PRDs, RFCs, ADRs, memos, runbooks, and briefs.

## Operating model

- Use Beads or the project's external tracker for durable task tracking.
- Use \`plan.md\` for the current implementation plan.
- Use this \`docs/\` tree for durable narrative artifacts and decision records.
- If multiple agent or harness sessions are active, use a single writer per file and coordinate handoffs in the tracker or \`plan.md\`.
- Prune stale sections and directories when they stop matching how the repo is actually run.

## Lanes

${laneLines.join("\n")}

## Core docs

- [Architecture](./architecture.md) — system shape, boundaries, invariants, and doc hierarchy

## Maintenance rule

If a document lane stops serving a real purpose, remove it or archive it intentionally. This tree should stay opinionated and current, not become a graveyard of stale templates.
`;
}

function buildArchitectureDoc(projectName, selectedLanes) {
  const laneLines = selectedLanes.map((lane) => {
    const label = DOC_LANES[lane]?.title ?? titleCase(lane);
    const desc = DOC_LANES[lane]?.description ?? "Custom documentation lane.";
    return `- **${label}** — ${desc}`;
  });

  return `<!--
docs/architecture.md — canonical architecture context and documentation-system contract.

Generated by \`construct init-docs\`. Update this file when the system shape,
ownership boundaries, or documentation operating model changes. Remove stale
assumptions as soon as they stop matching the codebase.
-->

# ${projectName} Architecture

## System overview

Describe the runtime shape, major modules, external dependencies, and key data boundaries.

## Project-state hierarchy

1. External tracker, preferably Beads, owns the durable backlog and issue status.
2. \`plan.md\` owns the current human-readable implementation plan.
3. cass-memory through MCP \`memory\` stores cross-session observations and preferences.
4. \`docs/\` stores durable narrative artifacts such as PRDs, RFCs, ADRs, memos, briefs, and runbooks.

## Documentation lanes

${laneLines.join("\n")}

## Key invariants

- Keep one source of truth per concern instead of parallel trackers.
- When multiple agent or harness sessions run in parallel, use a single writer per file.
- Update or prune stale docs when work changes project reality.
- Prefer adding a lane only when it has a distinct audience and decision rhythm.
`;
}

function buildLaneReadme(laneKey) {
  const lane = DOC_LANES[laneKey];
  const title = lane?.title ?? titleCase(laneKey);
  const description = lane?.description ?? "Custom documentation lane.";
  const dirName = lane?.dir ?? laneKey;
  const templateLines = (lane?.templates ?? []).map((templateName, index) => {
    const filename = index === 0 ? "_template.md" : templateName.replace(/\.md$/, ".template.md");
    return `- [${filename}](./${filename})`;
  });

  return `<!--
docs/${dirName}/README.md — lane guide for ${title}.

Generated by \`construct init-docs\`. Keep this lane focused on one document
family. If it no longer has a distinct purpose, prune it or merge it elsewhere.
-->

# ${title}

${description}

## Starter templates

${templateLines.join("\n")}
`;
}

function buildCustomLaneReadme(laneDir) {
  return `<!--
docs/${laneDir}/README.md — custom documentation lane.

Generated by \`construct init-docs\`. Rename, refine, or remove this lane once
its real purpose is clear. Do not keep placeholder structures around indefinitely.
-->

# ${titleCase(laneDir)}

Custom documentation lane for this project.

## Starter templates

- [\`_template.md\`](./_template.md)
`;
}

function buildCustomLaneTemplate(laneDir) {
  return `<!--
docs/${laneDir}/_template.md — starter template for a custom documentation lane.

Replace this with a real template once the lane's purpose is clear. If the lane
never becomes meaningful, delete the lane instead of keeping placeholder docs.
-->

# ${titleCase(laneDir)}: {title}

- **Date**: {YYYY-MM-DD}
- **Author**: {name}
- **Status**: draft | active | superseded

## Summary

<!-- What this document exists to explain or decide. -->

## Context

<!-- Why this matters now and what the reader needs to know first. -->

## Details

<!-- The actual content for this lane. -->

## Decisions or next steps

<!-- What changes because of this document. -->

## References

<!-- Links to related docs, code, or evidence. -->
`;
}

function titleCase(value) {
  return value
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function copyLaneTemplates(laneKey) {
  const lane = DOC_LANES[laneKey];
  if (!lane) return;
  const laneRoot = path.join(target, "docs", lane.dir);
  writeIfMissing(path.join(laneRoot, "README.md"), buildLaneReadme(laneKey));
  for (const [index, templateName] of lane.templates.entries()) {
    const sourcePath = path.join(TEMPLATE_DIR, templateName);
    const outputName = index === 0 ? "_template.md" : templateName.replace(/\.md$/, ".template.md");
    const content = fs.readFileSync(sourcePath, "utf8");
    writeIfMissing(path.join(laneRoot, outputName), content);
  }
}

function createCustomLane(laneDir) {
  const laneRoot = path.join(target, "docs", laneDir);
  writeIfMissing(path.join(laneRoot, "README.md"), buildCustomLaneReadme(laneDir));
  writeIfMissing(path.join(laneRoot, "_template.md"), buildCustomLaneTemplate(laneDir));
}

async function askQuestions() {
  if (skipInteractive) {
    return {
      lanes: docsArg ? parseCsvList(docsArg.split("=")[1]) : DEFAULT_LANES,
      extraLanes: extrasArg ? parseCsvList(extrasArg.split("=")[1]).map(normalizeCustomLaneName).filter(Boolean) : [],
    };
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  const ask = (prompt) => new Promise((resolve) => rl.question(prompt, resolve));

  process.stdout.write("A few quick questions to set up the docs surface:\n\n");
  const laneAnswer = await ask(`  Which documentation lanes do you want? [${DEFAULT_LANES.join(", ")}]\n  > `);
  process.stdout.write("\n");
  const extraAnswer = await ask("  Any custom lane directories to add under docs/? (comma-separated, blank for none)\n  > ");
  process.stdout.write("\n");
  rl.close();

  const lanes = laneAnswer.trim()
    ? parseCsvList(laneAnswer)
    : DEFAULT_LANES;
  const extraLanes = extraAnswer.trim()
    ? parseCsvList(extraAnswer).map(normalizeCustomLaneName).filter(Boolean)
    : [];

  return { lanes, extraLanes };
}

async function main() {
  const projectName = inferProjectName(target);
  const { lanes, extraLanes } = await askQuestions();
  const normalizedLanes = Array.from(new Set(
    lanes
      .map((lane) => lane.trim().toLowerCase())
      .filter((lane) => lane in DOC_LANES),
  ));
  const selectedLanes = normalizedLanes.length ? normalizedLanes : DEFAULT_LANES;
  const selectedCustomLanes = Array.from(new Set(
    extraLanes
      .map(normalizeCustomLaneName)
      .filter(Boolean)
      .filter((lane) => !(lane in DOC_LANES)),
  ));
  const allLaneKeys = [...selectedLanes, ...selectedCustomLanes];

  process.stdout.write(`\nConstruct init-docs → ${target}\n\n`);

  writeIfMissing(path.join(target, "docs", "README.md"), buildDocsReadme(projectName, allLaneKeys));
  writeIfMissing(path.join(target, "docs", "architecture.md"), buildArchitectureDoc(projectName, allLaneKeys));

  for (const laneKey of selectedLanes) copyLaneTemplates(laneKey);
  for (const laneKey of selectedCustomLanes) createCustomLane(laneKey);

  if (created.length) {
    process.stdout.write("Created:\n");
    for (const file of created) process.stdout.write(`  + ${file}\n`);
  }
  if (skipped.length) {
    process.stdout.write("\nSkipped (already exist):\n");
    for (const file of skipped) process.stdout.write(`  ~ ${file}\n`);
  }
  process.stdout.write(`\n${created.length} created, ${skipped.length} skipped.\n`);
}

main().catch((error) => {
  process.stderr.write(`Error: ${error.message}\n`);
  process.exit(1);
});
