/**
 * lib/providers/%%PROVIDER_NAME%%/index.mjs — %%PROVIDER_NAME%% provider.
 *
 * Capabilities: %%CAPABILITIES%%
 *
 * Generated by `construct scaffold provider %%PROVIDER_NAME%%`.
 * Replace every TODO comment with a real implementation before using this
 * provider in production.
 */
import { validateAllowlist } from '../contract.mjs';

const PROVIDER_NAME = '%%PROVIDER_NAME%%';

export function create({ env = process.env } = {}) {
  return {
    meta: {
      id: PROVIDER_NAME,
      displayName: '%%PROVIDER_NAME%%',
      capabilities: ['%%CAPABILITIES%%'],
      description: '%%PROVIDER_NAME%% provider (scaffolded — fill in details)',
    },

    configSchema: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {},
    },

    async health() {
      // Replace with a real connectivity check that returns { ok, detail }. // construct-lint-ignore
      return { ok: false, reason: 'not implemented' };
    },

    async read(resource, config = {}) {
      const check = validateAllowlist(PROVIDER_NAME, resource, config);
      if (!check.allowed) throw Object.assign(new Error(check.reason), { code: 'OUT_OF_SCOPE' });
      // Replace with a real fetch against the remote system. // construct-lint-ignore
      throw new Error('not implemented');
    },

    async search(query, config = {}) {
      // Replace with a real query against the remote system; return an array of items. // construct-lint-ignore
      throw new Error('not implemented');
    },
  };
}

export default create;
