#!/usr/bin/env node
/**
 * generate-docs.mjs — reference documentation derived from the definitions
 * that drive the product: the command registry, the broker tool definitions,
 * the configuration keys, the shipped skill and workflow catalog, and the
 * state model. `--check` regenerates in memory and fails when a committed
 * page differs, so a command, tool, key, bundle, or table cannot change
 * without its reference changing with it.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { COMMANDS } from '../src/cli/index.ts';
import { GLOBAL_FLAGS } from '../src/cli/commands.ts';
import { TOOLS, HEADLESS_FORBIDDEN } from '../src/kernel/broker/tools.ts';
import { CONFIG_KEYS } from '../src/kernel/project/config.ts';
import { createSkillRegistry } from '../src/kernel/registry/skill-registry.ts';
import { createWorkflowRegistry } from '../src/kernel/registry/workflow-registry.ts';
import { REQUIRED_TABLES, SCHEMA_SQL } from '../src/kernel/state/schema.ts';
import { RUN_TRANSITIONS } from '../src/kernel/state/runs.ts';
import { STEP_TRANSITIONS } from '../src/kernel/state/steps.ts';
import { TRUST_TRANSITIONS } from '../src/kernel/state/deliverables.ts';
import { TIER_POLICIES } from '../src/kernel/policy/lattice.ts';
import { BUILTIN_CAPABILITIES, BUILTIN_VALIDATORS } from '../src/kernel/registry/capability-registry.ts';

const DOCS = fileURLToPath(new URL('../docs/', import.meta.url));
const check = process.argv.includes('--check');
const HEADER = (what) => `<!-- Generated by scripts/generate-docs.mjs from ${what}. Do not edit by hand; run npm run docs:generate. -->\n\n`;

function table(headers, rows) {
  return [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`, ...rows.map((r) => `| ${r.map((c) => String(c).replaceAll('|', '\\|').replaceAll('\n', ' ')).join(' | ')} |`)].join('\n');
}

function cliReference() {
  const groups = [...new Set(COMMANDS.map((c) => c.group))];
  const parts = [HEADER('src/cli/index.ts'), '# Command line reference', '', 'Every command, its flags, and what it does. Every command accepts the global flags `--json`, `--debug`, and `--help`. Exit codes are 0 (done), 1 (could not complete), 2 (the command line was wrong); see [exit-codes.md](exit-codes.md).', ''];
  for (const g of groups) {
    parts.push(`## ${g}`, '');
    for (const c of COMMANDS.filter((x) => x.group === g)) {
      const usage = ['construct', ...c.path, ...c.positionals].join(' ');
      parts.push(`### \`${usage}\``, '', c.gloss, '');
      if (c.flags.length) parts.push(table(['Flag', 'Takes a value', 'Meaning'], c.flags.map((f) => [`\`--${f.name}\``, f.takesValue ? (f.repeatable ? 'yes, repeatable' : 'yes') : 'no', f.gloss])), '');
      parts.push(`Reads only: ${c.readOnly ? 'yes' : 'no'}.`, '');
    }
  }
  parts.push('## Global flags', '', table(['Flag', 'Meaning'], GLOBAL_FLAGS.map((f) => [`\`--${f.name}\``, f.gloss])), '');
  return parts.join('\n');
}

function brokerReference() {
  const parts = [HEADER('src/kernel/broker/tools.ts'), '# Broker reference (MCP)', '', 'The tools Construct offers an agent host over MCP. `construct serve` speaks newline-delimited JSON-RPC 2.0 over stdio and lists these under `tools/list`; input schemas are closed (undeclared keys are refused). The interactive surface serves the person\'s session; the headless surface serves an explicitly configured runner and never carries the tools marked interactive-only.', ''];
  for (const surface of ['interactive', 'headless']) {
    parts.push(`## ${surface === 'interactive' ? 'Interactive surface' : 'Headless surface'}`, '');
    for (const t of TOOLS.filter((x) => x.surface === 'both' || x.surface === surface)) {
      parts.push(`### \`${t.name}\``, '', `${t.title}. ${t.description}`, '', `Surface: ${t.surface}. Reads only: ${t.readOnly ? 'yes' : 'no'}.`, '');
      const props = Object.entries(t.inputSchema.properties);
      if (props.length) parts.push(table(['Input', 'Type', 'Required', 'Meaning'], props.map(([k, p]) => [`\`${k}\``, p.enum ? p.enum.map((e) => `\`${e}\``).join(', ') : p.type, (t.inputSchema.required ?? []).includes(k) ? 'yes' : 'no', p.description])), '');
    }
  }
  parts.push('## Never on the headless surface', '', HEADLESS_FORBIDDEN.map((n) => `- \`${n}\``).join('\n'), '');
  return parts.join('\n');
}

function configReference() {
  return [HEADER('src/kernel/project/config.ts'), '# Configuration reference', '', 'Five tiers, lowest first: built-in default, per-user presentation defaults (`$XDG_CONFIG_HOME/construct/config.json`), committed project config (`.construct/project.json` under `behavior`), environment, explicit flag. Each key names which tiers may set it. `construct config explain <key>` shows every tier\'s offer and the one that wins. A committed file can never grant consent, carry a secret, name an executable, or enable external writes; keys that would are refused.', '',
    table(['Key', 'Default', 'Set by', 'Environment', 'Flag', 'Meaning'], CONFIG_KEYS.map((k) => [`\`${k.key}\``, `\`${JSON.stringify(k.fallback)}\``, k.settableBy.join(', '), k.envVar ? `\`${k.envVar}\`` : '—', k.flag ? `\`${k.flag}\`` : '—', k.description])), ''].join('\n');
}

function catalog() {
  const skills = createSkillRegistry({ projectDir: null });
  const workflows = createWorkflowRegistry({ projectDir: null });
  const parts = [HEADER('the shipped skills/ and workflows/ bundles'), '# Skill and workflow catalog', '', 'What this version ships, with versions. Digests are in `registry/index.json`; a project pins what it resolved in `.construct/registry.lock.json`.', '', '## Skills', '',
    table(['Skill', 'Version', 'Category', 'Engages when', 'Stands down when'], skills.list().map((s) => [`\`${s.manifest.id}\``, s.manifest.version, s.manifest.category, s.manifest.activation[0], s.manifest.standDown[0]])), '', '## Workflows', '',
    table(['Workflow', 'Version', 'Class', 'Triggers', 'Steps', 'Purpose'], workflows.list().map((w) => [`\`${w.manifest.id}\``, w.manifest.version, w.manifest.interactionClass, w.manifest.triggers.join(', '), w.manifest.steps.map((s) => s.id).join(' → '), w.manifest.purpose])), '',
    '## Capabilities a step may require', '', table(['Capability', 'Tier', 'Kind', 'Meaning'], BUILTIN_CAPABILITIES.map((c) => [`\`${c.name}\``, c.tier, c.kind, c.description])), '', '## Validators a step may name', '', BUILTIN_VALIDATORS.map((v) => `- \`${v}\``).join('\n'), ''];
  return parts.join('\n');
}

function stateModel() {
  const tables = REQUIRED_TABLES.map((t) => {
    const m = new RegExp(`CREATE TABLE ${t} \\(([\\s\\S]*?)\\n\\);`).exec(SCHEMA_SQL);
    const cols = m ? m[1].split('\n').map((l) => l.trim()).filter((l) => /^[a-z_]+\s/.test(l) && !/^(CHECK|PRIMARY|UNIQUE|FOREIGN)/.test(l)).map((l) => l.split(/\s+/)[0]) : [];
    return [`\`${t}\``, cols.join(', ')];
  });
  const machine = (name, m) => [`### ${name}`, '', table(['From', 'To'], Object.entries(m).map(([k, v]) => [`\`${k}\``, v.length ? v.map((x) => `\`${x}\``).join(', ') : '(terminal)'])), ''].join('\n');
  return [HEADER('src/kernel/state/schema.ts and the state machines'), '# State model', '', 'One SQLite database per project at `.construct/state/construct.sqlite`, format `construct-state` 2. Foreign keys are on, multi-row transitions are transactional, the activity table is append-only by trigger, and any file not exactly this format is refused unread.', '', '## Tables', '', table(['Table', 'Columns'], tables), '', '## Lifecycles', '', machine('Run', RUN_TRANSITIONS), machine('Step', STEP_TRANSITIONS), machine('Deliverable trust', TRUST_TRANSITIONS), '## Action tiers', '', table(['Tier', 'Requirement', 'Meaning'], Object.values(TIER_POLICIES).map((p) => [`\`${p.tier}\``, p.requirement, p.description])), ''].join('\n');
}

const pages = { 'cli-reference.md': cliReference(), 'broker-reference.md': brokerReference(), 'config-reference.md': configReference(), 'catalog.md': catalog(), 'state-model.md': stateModel() };
let stale = [];
for (const [name, text] of Object.entries(pages)) {
  const path = `${DOCS}${name}`;
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== text) stale.push(name);
  } else {
    writeFileSync(path, text, 'utf8');
  }
}
if (check) {
  if (stale.length) {
    process.stderr.write(`generate-docs: stale — ${stale.join(', ')}\n  run: npm run docs:generate\n`);
    process.exit(1);
  }
  process.stdout.write(`generate-docs: current — ${Object.keys(pages).length} reference page(s)\n`);
} else {
  process.stdout.write(`generate-docs: wrote ${Object.keys(pages).join(', ')}\n`);
}
