/**
 * tests/scripts/inventory-sync-era.test.ts — leftover 2.x sync artifacts are
 * enumerated from markers and well-known locations, never from a hardcoded
 * file list, and the walk never writes.
 *
 * The live tree is Gerald's machines. These tests plant a miniature of it
 * under a tmpdir and pass --root, so they cannot touch HOME.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT = fileURLToPath(new URL('../../scripts/inventory-sync-era.mjs', import.meta.url));

function scan(root: string): {
  root: string;
  error?: string;
  projects: Array<{
    name: string;
    artifacts: Array<{ path: string; class: string; markers: string[] }>;
  }>;
} {
  const out = execFileSync(process.execPath, [SCRIPT, '--root', root, '--json'], {
    encoding: 'utf8',
  });
  return JSON.parse(out) as ReturnType<typeof scan>;
}

function plant(root: string, rel: string, body: string): string {
  const abs = join(root, rel);
  mkdirSync(join(abs, '..'), { recursive: true });
  writeFileSync(abs, body);
  return abs;
}

test('an empty tree reports no projects', () => {
  const root = mkdtempSync(join(tmpdir(), 'construct-inventory-'));
  try {
    const result = scan(root);
    assert.deepEqual(result.projects, []);
    assert.equal(result.root, root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('the known-litter project names surface when they carry sync-era files', () => {
  const root = mkdtempSync(join(tmpdir(), 'construct-inventory-'));
  try {
    plant(
      root,
      'blackstory/.cursor/rules/construct-web-hooks.mdc',
      '# leftover rule\n',
    );
    plant(
      root,
      'admin-app/.cursor/mcp.json',
      JSON.stringify({
        mcpServers: {
          'construct-mcp': { command: 'node', args: ['node_modules/@geraldmaron/construct/lib/mcp/server.mjs'] },
        },
      }),
    );
    plant(
      root,
      'geralddagher-site/.github/agents/construct.agent.md',
      '<!--\nGenerated by construct sync from registry/worker-profiles.\n-->\ncall orchestration_run\n',
    );
    plant(
      root,
      'oracle-app/.vscode/mcp.json',
      JSON.stringify({
        servers: {
          'construct-mcp': { command: 'node', args: ['/opt/@geraldmaron/construct/lib/mcp/server.mjs'] },
        },
      }),
    );
    plant(root, 'test-project/.github/prompts/.construct-manifest', 'construct.prompt.md\n');

    const result = scan(root);
    const names = result.projects.map((p) => p.name);
    assert.deepEqual(names, [
      'admin-app',
      'blackstory',
      'geralddagher-site',
      'oracle-app',
      'test-project',
    ]);

    const byName = Object.fromEntries(result.projects.map((p) => [p.name, p.artifacts]));
    assert.equal(byName.blackstory[0]?.class, 'cursor-rule');
    assert.equal(byName['admin-app'][0]?.class, 'cursor-mcp');
    assert.ok(byName['admin-app'][0]?.markers.includes('@geraldmaron/construct'));
    assert.equal(byName['geralddagher-site'][0]?.class, 'github-agent');
    assert.ok(byName['geralddagher-site'][0]?.markers.includes('Generated by construct sync'));
    assert.ok(byName['geralddagher-site'][0]?.markers.includes('orchestration_run'));
    assert.equal(byName['oracle-app'][0]?.class, 'vscode-mcp');
    assert.equal(byName['test-project'][0]?.class, 'github-prompt');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('the rewrite checkout and node_modules are not inventoried', () => {
  const root = mkdtempSync(join(tmpdir(), 'construct-inventory-'));
  try {
    plant(root, 'construct/.cursor/rules/construct-web-hooks.mdc', '# would look like litter\n');
    plant(
      root,
      'other/node_modules/@geraldmaron/construct/.cursor/rules/construct-x.mdc',
      'Generated by construct sync\n',
    );
    plant(root, 'other/.cursor/rules/construct-keep.mdc', '# real leftover\n');
    const result = scan(root);
    assert.deepEqual(
      result.projects.map((p) => p.name),
      ['other'],
    );
    assert.deepEqual(
      result.projects[0]?.artifacts.map((a) => a.path),
      ['.cursor/rules/construct-keep.mdc'],
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('a project skill without a Construct marker is not litter', () => {
  const root = mkdtempSync(join(tmpdir(), 'construct-inventory-'));
  try {
    plant(root, 'blackstory/.claude/skills/devops/git-workflow/SKILL.md', '# team skill\n');
    plant(
      root,
      'blackstory/.claude/skills/construct-docs/SKILL.md',
      'Generated by construct sync\n',
    );
    const result = scan(root);
    assert.equal(result.projects.length, 1);
    assert.deepEqual(
      result.projects[0]?.artifacts.map((a) => a.path),
      ['.claude/skills/construct-docs/SKILL.md'],
    );
    assert.equal(result.projects[0]?.artifacts[0]?.class, 'claude-skill');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

function filesUnder(dir: string): string[] {
  const out: string[] = [];
  const walk = (current: string) => {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const abs = join(current, entry.name);
      if (entry.isDirectory()) walk(abs);
      else if (entry.isFile()) out.push(abs);
    }
  };
  walk(dir);
  return out.sort();
}

test('the inventory does not write', () => {
  const root = mkdtempSync(join(tmpdir(), 'construct-inventory-'));
  try {
    const file = plant(root, 'admin-app/.cursor/rules/construct-web-hooks.mdc', '# leftover\n');
    const before = readFileSync(file);
    const beforeTree = filesUnder(root);
    scan(root);
    assert.deepEqual(readFileSync(file), before, 'file bytes must be unchanged');
    assert.deepEqual(filesUnder(root), beforeTree, 'no files may appear or vanish');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
