/**
 * tests/scripts/inventory-sync-era.test.ts — the sweep's two load-bearing
 * judgments: what counts as a marker hit, and what counts as this repo.
 *
 * Both are read-only, fixture-rooted checks. Nothing here touches a real
 * project tree or a real $HOME — every fixture is a tmpdir built and torn
 * down per test, the same shape tests/kernel/cleanup/catalog.test.ts uses for
 * the predecessor's own detection catalog.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
// @ts-expect-error — the script is plain .mjs, deliberately outside src/
import { markersIn, looksLikeConstructRepo, scanCursorRules, scanCursorMcp, scanSkillsTree, scanGithubAgents, scanGithubPrompts, scanProject, inventory } from '../../scripts/inventory-sync-era.mjs';

function mkTmp(prefix: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function write(filePath: string, content: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
}

// ---------------------------------------------------------------------------
// markersIn
// ---------------------------------------------------------------------------

test('markersIn finds each generation marker independently', () => {
  assert.deepEqual(markersIn('<!-- Generated by construct sync -->'), [
    'Generated by construct sync',
  ]);
  assert.deepEqual(markersIn('depends on @geraldmaron/construct'), ['@geraldmaron/construct']);
  assert.deepEqual(markersIn('const orchestration_run = true;'), ['orchestration_run']);
});

test('markersIn returns every marker present, and none for ordinary text', () => {
  const text = 'Generated by construct sync, using @geraldmaron/construct, orchestration_run=1';
  assert.deepEqual(markersIn(text), [
    'Generated by construct sync',
    '@geraldmaron/construct',
    'orchestration_run',
  ]);
  assert.deepEqual(markersIn('an ordinary project file with no markers'), []);
  assert.deepEqual(markersIn(''), []);
});

// ---------------------------------------------------------------------------
// looksLikeConstructRepo
// ---------------------------------------------------------------------------

test('looksLikeConstructRepo is true only for the exact published package name', () => {
  const dir = mkTmp('construct-inv-repo-');
  try {
    write(path.join(dir, 'package.json'), JSON.stringify({ name: '@geraldmaron/construct' }));
    assert.equal(looksLikeConstructRepo(dir), true);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('looksLikeConstructRepo is false for an unrelated project, a missing package.json, and malformed JSON', () => {
  const unrelated = mkTmp('construct-inv-unrelated-');
  const missing = mkTmp('construct-inv-missing-');
  const malformed = mkTmp('construct-inv-malformed-');
  try {
    // A project merely NAMED "construct" must not match — the signal is the
    // published package name, not a directory basename guess.
    write(path.join(unrelated, 'package.json'), JSON.stringify({ name: 'construct' }));
    assert.equal(looksLikeConstructRepo(unrelated), false);

    assert.equal(looksLikeConstructRepo(missing), false);

    write(path.join(malformed, 'package.json'), '{ not json');
    assert.equal(looksLikeConstructRepo(malformed), false);
  } finally {
    fs.rmSync(unrelated, { recursive: true, force: true });
    fs.rmSync(missing, { recursive: true, force: true });
    fs.rmSync(malformed, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// Per-target-location scans
// ---------------------------------------------------------------------------

test('scanCursorRules matches only construct-*.mdc files, and only when a marker is inside', () => {
  const dir = mkTmp('construct-inv-rules-');
  try {
    write(
      path.join(dir, '.cursor', 'rules', 'construct-legacy.mdc'),
      'Generated by construct sync\nsome rule body',
    );
    // Same directory, filename doesn't match the glob: never searched.
    write(path.join(dir, '.cursor', 'rules', 'unrelated.mdc'), 'orchestration_run');
    // Matches the glob but carries no marker: not a hit.
    write(path.join(dir, '.cursor', 'rules', 'construct-clean.mdc'), 'nothing marked here');

    const notes: string[] = [];
    const hits = scanCursorRules(dir, notes);
    assert.equal(hits.length, 1);
    assert.equal(hits[0].class, 'cursor-rule');
    assert.equal(hits[0].marker, 'Generated by construct sync');
    assert.equal(hits[0].file, path.join('.cursor', 'rules', 'construct-legacy.mdc'));
    assert.deepEqual(notes, []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('scanCursorRules also matches bare construct.mdc and construct.<word>.mdc, not only the hyphenated form', () => {
  const dir = mkTmp('construct-inv-rules-forms-');
  try {
    // The front-door rule file — no separator at all after "construct".
    write(path.join(dir, '.cursor', 'rules', 'construct.mdc'), 'Generated by construct sync');
    // A dotted variant, the other named form.
    write(path.join(dir, '.cursor', 'rules', 'construct.legacy.mdc'), '@geraldmaron/construct');
    // Starts with "construct" but has no separator before its own word —
    // must still not match, the same way "construct-*" never matched
    // "constructive-something.mdc".
    write(path.join(dir, '.cursor', 'rules', 'constructive.mdc'), 'orchestration_run');

    const notes: string[] = [];
    const hits = scanCursorRules(dir, notes);
    assert.deepEqual(
      hits.map((h: { file: string }) => h.file).sort(),
      [path.join('.cursor', 'rules', 'construct.legacy.mdc'), path.join('.cursor', 'rules', 'construct.mdc')].sort(),
    );
    assert.deepEqual(notes, []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('scanCursorRules with no .cursor/rules directory reports no hits and no note', () => {
  const dir = mkTmp('construct-inv-norules-');
  try {
    const notes: string[] = [];
    assert.deepEqual(scanCursorRules(dir, notes), []);
    assert.deepEqual(notes, [], 'a directory simply not existing is not an error to report');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('scanCursorMcp parses mcpServers entries rather than grepping the raw file', () => {
  const dir = mkTmp('construct-inv-mcp-');
  try {
    write(
      path.join(dir, '.cursor', 'mcp.json'),
      JSON.stringify({
        // A marker sitting OUTSIDE mcpServers must not produce a hit — this is
        // exactly what a whole-file text grep would over-match on.
        _comment: 'orchestration_run appears here but is not a server entry',
        mcpServers: {
          'construct-mcp': {
            command: 'node',
            args: ['/path/to/@geraldmaron/construct/bin/construct.mjs', 'serve'],
          },
          github: { command: 'npx', args: ['-y', 'github-mcp'] },
        },
      }),
    );
    const notes: string[] = [];
    const hits = scanCursorMcp(dir, notes);
    assert.equal(hits.length, 1);
    assert.equal(hits[0].class, 'mcp-entry');
    assert.equal(hits[0].marker, '@geraldmaron/construct');
    assert.equal(hits[0].detail, 'mcpServers.construct-mcp');
    assert.deepEqual(notes, []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('scanCursorMcp handles a missing file and malformed JSON without throwing', () => {
  const missing = mkTmp('construct-inv-mcp-missing-');
  const malformed = mkTmp('construct-inv-mcp-malformed-');
  try {
    assert.deepEqual(scanCursorMcp(missing, []), []);

    write(path.join(malformed, '.cursor', 'mcp.json'), '{ not json at all');
    const notes: string[] = [];
    assert.deepEqual(scanCursorMcp(malformed, notes), []);
    assert.ok(notes.some((n) => n.includes('malformed JSON')));
  } finally {
    fs.rmSync(missing, { recursive: true, force: true });
    fs.rmSync(malformed, { recursive: true, force: true });
  }
});

test('scanSkillsTree, scanGithubAgents, scanGithubPrompts walk their trees recursively and skip node_modules', () => {
  const dir = mkTmp('construct-inv-trees-');
  try {
    write(
      path.join(dir, '.claude', 'skills', 'deploy', 'nested', 'SKILL.md'),
      '<!-- Generated by construct sync -->',
    );
    write(
      path.join(dir, '.claude', 'skills', 'node_modules', 'pkg', 'file.md'),
      'orchestration_run',
    );
    write(path.join(dir, '.github', 'agents', 'construct.md'), 'orchestration_run');
    write(path.join(dir, '.github', 'prompts', 'sync.md'), '@geraldmaron/construct');

    const skillHits = scanSkillsTree(dir, []);
    assert.equal(skillHits.length, 1, 'node_modules under the tree must not be walked');
    assert.equal(skillHits[0].class, 'skills-tree');
    assert.equal(
      skillHits[0].file,
      path.join('.claude', 'skills', 'deploy', 'nested', 'SKILL.md'),
    );

    const agentHits = scanGithubAgents(dir, []);
    assert.equal(agentHits.length, 1);
    assert.equal(agentHits[0].class, 'github-agent');

    const promptHits = scanGithubPrompts(dir, []);
    assert.equal(promptHits.length, 1);
    assert.equal(promptHits[0].class, 'github-prompt');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('scanGithubAgents and scanGithubPrompts name an orphaned .construct-manifest sidecar, which carries no marker of its own', () => {
  const dir = mkTmp('construct-inv-manifest-');
  try {
    // Each sidecar's whole content is the filename of the artifact it used
    // to sit beside — no generated-artifact file exists here, matching the
    // deleted-artifact state a real orphaned sidecar is found in.
    write(path.join(dir, '.github', 'agents', '.construct-manifest'), 'construct.agent.md\n');
    write(path.join(dir, '.github', 'prompts', '.construct-manifest'), 'construct.prompt.md\n');

    const agentHits = scanGithubAgents(dir, []);
    assert.equal(agentHits.length, 1, 'no marker anywhere in this tree — the sidecar itself is the only signal');
    assert.equal(agentHits[0].class, 'github-agent-manifest');
    assert.equal(agentHits[0].file, path.join('.github', 'agents', '.construct-manifest'));
    assert.equal(agentHits[0].detail, 'construct.agent.md', 'names the deleted artifact it pointed at');

    const promptHits = scanGithubPrompts(dir, []);
    assert.equal(promptHits.length, 1);
    assert.equal(promptHits[0].class, 'github-prompt-manifest');
    assert.equal(promptHits[0].detail, 'construct.prompt.md');
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('scanGithubAgents reports both a marker hit and a manifest sidecar when a tree carries both', () => {
  const dir = mkTmp('construct-inv-manifest-both-');
  try {
    write(path.join(dir, '.github', 'agents', 'still-generated.md'), 'orchestration_run');
    write(path.join(dir, '.github', 'agents', '.construct-manifest'), 'deleted.agent.md\n');

    const hits = scanGithubAgents(dir, []);
    assert.equal(hits.length, 2);
    assert.deepEqual(hits.map((h: { class: string }) => h.class).sort(), ['github-agent', 'github-agent-manifest']);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('an unreadable target location is skipped and noted, never thrown', () => {
  const dir = mkTmp('construct-inv-unreadable-');
  try {
    // .claude/skills exists as a FILE, not a directory: readdirSync on it
    // throws ENOTDIR, standing in for any fs error a real permission-denied
    // subdirectory would raise.
    write(path.join(dir, '.claude', 'skills'), 'not a directory');
    const notes: string[] = [];
    const hits = scanSkillsTree(dir, notes);
    assert.deepEqual(hits, []);
    assert.equal(notes.length, 1);
    assert.match(notes[0], /skipped .*skills/);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

// ---------------------------------------------------------------------------
// scanProject + inventory (the root walk)
// ---------------------------------------------------------------------------

test('scanProject combines all five target locations for one project', () => {
  const dir = mkTmp('construct-inv-project-');
  try {
    write(
      path.join(dir, '.cursor', 'rules', 'construct-synced.mdc'),
      'Generated by construct sync',
    );
    write(path.join(dir, '.github', 'prompts', 'p.md'), 'orchestration_run');
    const { hits, notes } = scanProject(dir);
    assert.equal(hits.length, 2);
    assert.deepEqual(notes, []);
    assert.deepEqual(
      hits.map((h: { class: string }) => h.class).sort(),
      ['cursor-rule', 'github-prompt'],
    );
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('inventory finds a project littered only with the two classes the walk used to miss', () => {
  // Mirrors the real shape this fix was written for: a bare construct.mdc
  // (fails the old hyphen-only glob) plus orphaned manifest sidecars under
  // both .github/agents and .github/prompts (carry no marker at all) — no
  // hyphenated rule file and no marker-bearing agent/prompt file anywhere,
  // so a scan that only had the old regex and the old marker search would
  // report this project clean.
  const root = mkTmp('construct-inv-missed-classes-');
  try {
    write(
      path.join(root, 'legacy-project', '.cursor', 'rules', 'construct.mdc'),
      '<!-- Generated by construct sync -->',
    );
    write(
      path.join(root, 'legacy-project', '.github', 'agents', '.construct-manifest'),
      'construct.agent.md\n',
    );
    write(
      path.join(root, 'legacy-project', '.github', 'prompts', '.construct-manifest'),
      'construct.prompt.md\n',
    );

    const result = inventory(root);
    assert.equal(result.status, 'ok');
    assert.equal(result.scanned, 1);
    assert.equal(result.projects.length, 1);
    const [project] = result.projects;
    assert.equal(project.hits.length, 3);
    assert.deepEqual(
      project.hits.map((h: { class: string }) => h.class).sort(),
      ['cursor-rule', 'github-agent-manifest', 'github-prompt-manifest'],
    );
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

test('inventory reports a missing root as status no-root, exit-worthy but not an error', () => {
  const root = path.join(os.tmpdir(), 'construct-inv-does-not-exist-' + String(process.pid));
  const result = inventory(root);
  assert.equal(result.status, 'no-root');
  assert.equal(result.reason, 'does not exist');
});

test('inventory walks immediate children as projects, excludes this repo, and stays silent about clean ones', () => {
  const root = mkTmp('construct-inv-root-');
  try {
    // A littered project.
    write(
      path.join(root, 'littered', '.cursor', 'rules', 'construct-synced.mdc'),
      'Generated by construct sync',
    );
    // A clean project — nothing under any target location.
    fs.mkdirSync(path.join(root, 'clean-project'), { recursive: true });
    // This repo, by package.json name — must be excluded, not merely clean.
    write(
      path.join(root, 'construct', 'package.json'),
      JSON.stringify({ name: '@geraldmaron/construct' }),
    );
    write(
      path.join(root, 'construct', '.github', 'prompts', 'p.md'),
      'orchestration_run — must never surface, this project is excluded',
    );
    // node_modules sitting directly at the root is not itself a "project" in
    // the sense the sweep cares about, but it must never be walked into if
    // treated as one — cover it by also nesting an inner node_modules.
    write(
      path.join(root, 'littered', 'node_modules', 'dep', 'file.md'),
      'orchestration_run',
    );

    const result = inventory(root);
    assert.equal(result.status, 'ok');
    assert.equal(result.excludedConstructRepo, 1);
    assert.equal(result.scanned, 2, 'littered + clean-project, not the excluded repo look-alike');
    assert.equal(result.clean, 1);

    const names = result.projects.map((p: { name: string }) => p.name);
    assert.deepEqual(names, ['littered'], 'only the project with a hit is listed');

    const littered = result.projects[0];
    assert.equal(littered.hits.length, 1);
    assert.equal(littered.hits[0].marker, 'Generated by construct sync');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});
